### ISSUE TITLE
Quality options on VOD download not working?

### ISSUE THREAD

**Issue by fefo-dev** [crackededed/Xtra#103]
Tested on several videos of several channels and only the source quality is available. I can click the arrow, which I believe should open a drop-down menu with selectable resolutions, but nothing happens.

Is there any limitation on how you download VODs from Twitch? Since I couln't find any related issue I don't know if it's possible or not.

Much appreciated.

**Comment by crackededed** [comment]
the menu should have at least source and audio only. so maybe the ui isn't working. what device and rom are you using?

**Comment by fefo-dev** [comment]
Moto G5, Android 9 (Lineage OS)

Most certainly should be the UI, as nothing pops to me. Thought it had someting to do with Animator animations, since disabling it often breaks some specific animations, but testing with either had the same results.

Here's a video to illustrate (recorded on scrcpy, hence the mouse):

https://user-images.githubusercontent.com/53354796/178118586-84786b6a-63a5-4f5d-b1c3-9cb3011d0ed6.mp4

**Comment by crackededed** [comment]
try the drop down menu on clip download dialog and game pages as well

**Comment by fefo-dev** [comment]
Clips no, Games yes - also works after disabling tabs on Following and Downloads. Maybe the drop down is drawn behind the pop out window? Dunno.

**Comment by fefo-dev** [comment]
@crackededed somehow it has something to do with DPI changes making it open WAY off where it should:

[](https://i.imgur.com/CHEifT0.png)
More examples:
https://i.imgur.com/KHSeQaH.png
https://i.imgur.com/ROxHt52.png

Now I couldn't find what causes this to happen only on my device; doing the same on another phone works accordingly, while on mine no available setting could fix it. If you got any clue I'd be happy to test.

**Comment by crackededed** [comment]
i don't know what could be changed in the code to make it work. updating lineage os would probably fix it. if you want to try updating i think this is the link for your device: https://download.lineageos.org/cedric

**Comment by fefo-dev** [comment]
Found the culprit by chance: enabling Expanded Desktop (system-wide immersive fullscreen) on LOS. Maybe lack of immersive mode on Xtra causes/exacerbates this, but in years using this setting that as a first.

Anyway, this feature was deprecated on latter LOS so I'm just documenting the bug.

Thanks a lot.
