### ISSUE TITLE
emotes only showing text

### ISSUE THREAD

**Issue by elliotalderon25** [crackededed/Xtra#106]
i'm from latin america if that matters

**Comment by crackededed** [comment]
what android version are you on? do recent messages get loaded when connecting to chat? does the login page load?

**Comment by elliotalderon25** [comment]
> what android version are you on? do recent messages get loaded when connecting to chat? does the login page load?

8.1.0, yes and yes. classic twitch emotes are fine, bttv, ffz and 7tv animated ones don't work

**Comment by Cuddle0456** [comment]
Something similar happens to me as well, gif emotes are showing as png/jpg image emotes they are not animated as they should have and also my android version is 8.1.0 as well.

**Comment by Cuddle0456** [comment]
If you don't mind Could we get an update on this @crackededed ?

**Comment by crackededed** [comment]
is it all gifs or only some?

**Comment by Cuddle0456** [comment]
> is it all gifs or only some?

As far as I have seen all of the gifs.

**Comment by elliotalderon25** [comment]
I had the app tunninstaled for a week now and now is working fine
