### ISSUE TITLE
Channels with any broadcast, are shown on top when sorted as Last Broadcast/Descending 

### ISSUE THREAD

**Issue by LukasThyWalls** [crackededed/Xtra#115]
Hello.

To explain this, nothing better than a screenshot:
![Xtra_ChannelsWithNoBroadcast_AreOnTop](https://user-images.githubusercontent.com/1467366/180614031-c3e91947-2c31-491e-9d86-63f337e24929.jpg)

The Channels are sorted by Last Broadcast/Descending, so, the channels with more recent broadcast should be shown on top. However, Those three channels with no broadcast at all are shown above the ones with most recent broadcasts.

Those channels should be put in the bottom list in that case.

If the sort is put in "Ascending" is the opposite, those channels are put in the bottom when they should be put in the top.

Thanks!

**Comment by crackededed** [comment]
i think it's fixed now

**Comment by LukasThyWalls** [comment]
Fixed in 2.3.2. Thanks!

Closing.
