### ISSUE TITLE
Feature Request : Display the English (latin script) versions of CN/KR/JP character Streamer names

### ISSUE THREAD

**Issue by gvdvg** [crackededed/Xtra#119]
As of now, I have to open chat to get the "Connected to USERNAME" message to find out.  Also it's not every streamer, some display as the English version, maybe it's up to the streamer which is default. I'm assuming all usernames have an English type-able version...
Maybe you could have a toggle to 'Force English' or have one or the other in brackets
Maybe it could be an option for chat usernames as well
I always use this app not logged in to twitch, if that's important

thanks

**Comment by crackededed** [comment]
added
