### ISSUE TITLE
Remove cancel option on notification when downloading VOD

### ISSUE THREAD

**Issue by CrimsonBloodfang** [crackededed/Xtra#120]
That's a problematic option when pressed accidentally. 

It just happened to me, I woke up half asleep and tried to switch to Xtra downloads by pressing the download notification and I later found out that the downloaded .ts were completely deleted. 

If a user really wants to delete the download, let them delete it only from the download tab which has a confirmation dialog.

**Comment by crackededed** [comment]
it's removed now
