### ISSUE TITLE
Complete the .m3u8 file first while downloading

### ISSUE THREAD

**Issue by CrimsonBloodfang** [crackededed/Xtra#122]
I have been opening the .m3u8 file with MX Player to watch VODs while it's downloading. It would be nice if the .m3u8 could complete listing the number of .ts files beforehand so we can just use it to watch while downloading. 

I also have a 12:43:10 duration .m3u8 file saved and the trick I use is by opening it with MiXplorer's text editor and replacing all the folder path with the new one. 
If the vod downloading doesn't start at 0.ts, I just delete the .ts that aren't included from the .m3u8 file, because they just buffer MX Player.

It would also be great if someone could provide us a 25 hour .m3u8 file to edit or if someone knows how to create one.

**Comment by magne4000** [comment]
I would even suggest to add the ability to play a downloading video if that's possible

**Comment by crackededed** [comment]
it's possible to watch while downloading now
