### ISSUE TITLE
Not all usernames appear on @...

### ISSUE THREAD

**Issue by CrazyWolf13** [crackededed/Xtra#125]
If user abc12 writes something in Chat and i want to respond, i type @ abc123 but if i type @ ab there mostly is no name in the list which i could choose so only a small drop of all users are really in this list. So mostly i have to type all those usernames by hand which is kinda annoying cause in the original app it works.

Thanks for your great application please keep it up. I also could watch twitch with such a high resolution and for such a long time without twitch killing my battery und overheating my phone lol

**Comment by crackededed** [comment]
they all seem to appear fine for me. maybe it stops showing new names when there's too many to show or something

**Comment by CrazyWolf13** [comment]
No, if i type as example (i want to @ User 1234) @ User12 there is just nothing in the list above the chat field, the user has written in chat but i have to manually enter his name i also have no idea why.

**Comment by CrazyWolf13** [comment]
Seems to happen only in huge channels with some thousand ppl.

**Comment by CrazyWolf13** [comment]
As example here i tried to ping @ honeycube88 but the menu showed nothing, but he has written to chat.
![Uploading Screenshot_20220811-154534_Xtra.jpg…]()

**Comment by CrazyWolf13** [comment]
![Uploading Screenshot_20220811-154534_Xtra.jpg…]()

**Comment by CrazyWolf13** [comment]
![Screenshot_20220811-154534_Xtra_copy_768x1664](https://user-images.githubusercontent.com/96661824/184149783-2f9689f9-9d61-4a72-a4a4-b1e5ddaf76cd.jpg)

**Comment by crackededed** [comment]
i'm pretty sure this was fixed in 2.17.0
