### ISSUE TITLE
Raids 

### ISSUE THREAD

**Issue by CrazyWolf13** [crackededed/Xtra#126]
Would be a nice feature to get raids working.

**Comment by Racoon62** [comment]
![IMG_20220810_030031](https://user-images.githubusercontent.com/97580150/183782009-7e07b177-477a-42cc-8fb6-6d2250afd094.jpg)

**Comment by CrazyWolf13** [comment]
![Screenshot_20220810-063112_Xtra](https://user-images.githubusercontent.com/96661824/183816361-c1375157-e1a8-4e21-ab8d-9de56578739c.jpg)

**Comment by CrazyWolf13** [comment]
Thanks for this, i had to manually update, and idk why , but now it works thanks
