### ISSUE TITLE
Missing `duration` usage for `irc_notice_usage_followers_on`

### ISSUE THREAD

**Issue by adem4ik** [crackededed/Xtra#131]
The following string in strings.xml seems to be missing something important:
https://github.com/crackededed/Xtra/blob/master/app/src/main/res/values/strings.xml#L371
`<string name="irc_notice_usage_followers_on">Usage: “/followers`

I guess it should look like this:
`<string name="irc_notice_usage_followers_on">Usage: “/followers” duration`

**Comment by crackededed** [comment]
fixed
