### ISSUE TITLE
[Suggestion] Don't reload the video if you tap on the same already playing stream

### ISSUE THREAD

**Issue by adem4ik** [crackededed/Xtra#133]
**Version:** 2.4.3 (latest)

1. Open any stream from Following
2. Minimize the current stream (so you have Following opened with the preview of the played stream)
3. Tap on the same stream as the previewed one in the Following list

**Result:** Stream starting to load
**Suggested result:** Expand the stream from the preview w/o reloading

![image](https://user-images.githubusercontent.com/4707112/184637750-d94d0dcc-7691-4e2c-9c33-f8621816cf0c.png)

**Comment by CrazyWolf13** [comment]
No i actually see this as a feature if the streams hangs or something doesn't work or chat disconnected and with this i can easily reload the stream.

> **Version:** 2.4.3 (latest)
> 
> 1. Open any stream from Following
> 2. Minimize the current stream (so you have Following opened with the preview of the played stream)
> 3. Tap on the same stream as the previewed one in the Following list
> 
> **Result:** Stream starting to load **Suggested result:** Expand the stream from the preview w/o reloading
> 
> ![image](https://user-images.githubusercontent.com/4707112/184637750-d94d0dcc-7691-4e2c-9c33-f8621816cf0c.png)

**Comment by adem4ik** [comment]
I guess it is better to close that issue as it was explained.
