### ISSUE TITLE
Very low framerate on 60fps stream.

### ISSUE THREAD

**Issue by herculess89** [crackededed/Xtra#139]
I have a samsung galaxy a7 2020 tablet and when i use 1080p60 it runs on very low fps, switching to 720p60 doesnt fix it. This happened after the new exoplayer update. The old exoplayer version works well but has other bugs like crashing in audio mode and while switching apps.

**Comment by herculess89** [comment]
No, stock android 12 One UI 4.1.

**Comment by crackededed** [comment]
https://github.com/crackededed/Xtra/issues/197#issuecomment-1369041194
