### ISSUE TITLE
TTVLOL erro

### ISSUE THREAD

**Issue by Vinnnes** [crackededed/Xtra#148]
I'm experiencing video playback error, it always gives "TTVLOL offline" error...

**Comment by Vinnnes** [comment]
A print of the errorA print of the error
![Screenshot_20220831-015032_1](https://user-images.githubusercontent.com/107320260/187595246-6a90a627-e3fe-48a4-be77-d73836bec95f.png)

**Comment by oatberry** [comment]
Is there any information anywhere about how TTV.LOL works? It would sure be nice if we didn't have to depend on this one random service...

**Comment by axopoulos** [comment]
Same here

**Comment by ejkoem15** [comment]
Same
