### ISSUE TITLE
Bug and Feature Request

### ISSUE THREAD

**Issue by trappininthevoidd** [crackededed/Xtra#15]
The app closes after selecting "audio only".  Is it possible to add background playback without a selection?
https://user-images.githubusercontent.com/99685018/154507846-4e68c65e-a0fc-4057-a52a-7cd06255b26a.mp4

https://bin.kv2.dev/~620e625a410e7c32e6699603

**Comment by crackededed** [comment]
audio only crashes because the player used in xtra needs to be updated. background playback should be possible but idk how to do it at this time
