### ISSUE TITLE
When stream ends, screen remains on.

### ISSUE THREAD

**Issue by jippyuk** [crackededed/Xtra#150]
I know there is a sleep button for turning off the display.
I've noticed several times that when I forget to turn on sleep mode, when the the stream ends, it will very often remain on the end screen of the broadcaster even if the stream is ended. Display remains on all night (if you fall asleep :) )
Means battery / drain heatup and burnin if you did it a lot.

**Comment by natapov** [comment]
@crackededed This has caused my screen to stay on all night more times than I can count.

**Comment by crackededed** [comment]
should be fixed now

**Comment by jippyuk** [comment]
Thanks so much for fixing this!
