### ISSUE TITLE
Add Material You icon

### ISSUE THREAD

**Issue by Darkempire78** [crackededed/Xtra#151]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

Since android 13 icons should follow Material You. This is very simple to do

**Comment by balkaransamra** [comment]
Would be nice. Doesn't need a full material you redesign either, just the icon.

**Comment by crackededed** [comment]
i don't know how to do it

![Screenshot_1672998402](https://user-images.githubusercontent.com/90209774/210975860-6e6fa5e6-2a53-4adb-a4de-c901ca3f3ced.png)
