### ISSUE TITLE
Ad blocker not working

### ISSUE THREAD

**Issue by Donkey-Doug** [crackededed/Xtra#154]
The ad blocker does not seem to be working for me

**Comment by axopoulos** [comment]
updated to app latest version and adblock not working

**Comment by daylightEX** [comment]
Yeah. I'm on the latest version downloaded from F-Droid and it is still not working.

**Comment by Jaladhjin** [comment]
> in case you have a dns filter (for example a pihole) you can block `server ethicalads io` (with dots, not spaces).

Why would blocking that server block ads on Twitch?

What does that server have to do with Twitch?

If it works hey awesome I'm just interested how it ties into the mix.
