### ISSUE TITLE
(Feature request) Bypass 720p limit

### ISSUE THREAD

**Issue by RoonMoonlight** [crackededed/Xtra#160]
Starting from September 30 2022, the 720p limitation will apply to Twitch with Korea region, which is very annoying.

Is there any ways to bypass this limit, please add that feature.

**Comment by RoonMoonlight** [comment]
Related article:
https://twitter.com/zachbussey/status/1575326770735226880

**Comment by crackededed** [comment]
probably just having ttv lol enabled will bypass this since it should get the stream playlist from other regions

**Comment by RoonMoonlight** [comment]
Yeah I found that information! Glad this client supports TTV LOL support, thanks anyways!

**Comment by Arc-Jung** [comment]
@crackededed 
How long develope TTV LOL feature?

**Comment by Arc-Jung** [comment]
@crackededed 
@RoonMoonlight 
Setting -> Use Adblocker
i found TTV LOL option in app.

**Comment by RoonMoonlight** [comment]
Yeah I noticed, thank you (Now closing issue)

**Comment by Arc-Jung** [comment]
![Screenshot_20220930_154215_Xtra](https://user-images.githubusercontent.com/43470915/193208755-a66a2714-5507-478b-9c0f-15a96609c751.jpg)
I upload screenshot.
