### ISSUE TITLE
Channel sort by time followed doesn't apply sort direction

### ISSUE THREAD

**Issue by SebiderSushi** [crackededed/Xtra#163]
On the "Following" tag sorting channels by "Time followed" descending and ascending order both give the same result. Channels are always sorted from least to most recently followed. There is no way to sort most recently followed channels to the top.

### Additional info
App version: 2.6.4 (135) from F-Droid
All channels are followed locally.
There is no Twitch account logged into the app.

**Comment by crackededed** [comment]
fixed

**Comment by SebiderSushi** [comment]
awesome, thanks!
