### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mediapinta** [crackededed/Xtra#166]
Hi,

I'm trying to install Xtra trough F-Droid app and I just get a "Not installed" error message.

Android 12 SKQ.211103.001
MIUI Global 13.0.1
Redmi 10C

Any help?

Thank you

Greetings,
ifrit

**Comment by AndreyAsadchy** [comment]
If you currently have a version from GitHub, you need to uninstall it.

**Comment by mediapinta** [comment]
I didn't have any previous version.

**Comment by AndreyAsadchy** [comment]
Did you grant the permission to install apps for f-droid?

**Comment by mediapinta** [comment]
Yes, I did. I installed many apps from there before (AntennaPod, Element, Twidere, StreetComplete...)

**Comment by crackededed** [comment]
if you don't have any previous versions installed then some kind of log is probably needed
