### ISSUE TITLE
Xtra does not collect points 

### ISSUE THREAD

**Issue by Kubix606** [crackededed/Xtra#167]
When I use Xtra, I noticed that I am not collecting points and I cannot spend them (icon is not visible)

I even set it up to collect points by itself, but it did nothing. Please fix this and if this is any mistake on my part, please tell me. 

I greet warmly

**Comment by crackededed** [comment]
check if you have a GQL token:
Settings -> Api settings -> Tokens -> GQL token

**Comment by crackededed** [comment]
actually it has the same problem as follow button so it doesn't work at the moment

**Comment by Kubix606** [comment]
> actually it has the same problem as follow button so it doesn't work at the moment

Alright, but please repair it.
Thank you
