### ISSUE TITLE
unable to log in 

### ISSUE THREAD

**Issue by jeremylaier** [crackededed/Xtra#178]
Logging in returns 404 page not found error

following instructions under "help logging in" also give same error and a useless url of `id.twitch.tv/ouath2/'` yes, that `'` is included at the end by default when using an external browser

**Comment by crackededed** [comment]
logging in or just opening the login page? maybe try clearing the app data to restore default settings.

**Comment by Daxuli** [comment]
I've also had issues today logging in (the app just kept loading after entering two-factor authentication code). Clearing app data solved the problem, thanks

**Comment by crackededed** [comment]
this was an issue with twitch servers
