### ISSUE TITLE
Commercial break in progress

### ISSUE THREAD

**Issue by Empakt** [crackededed/Xtra#182]
Consistently when I open some streams (xQc in this example) I'm being presented with this view for 30 seconds. For streams where this occurs, it happens every time, on other streams it hasn't appeared once.
![Screenshot_2022-11-08-14-44-08-543_com github andreyasadchy xtra](https://user-images.githubusercontent.com/93092498/200582913-ae33c5b8-b177-4b17-b74e-dce5e30e69b1.jpg)

**Comment by crackededed** [comment]
turn off adblock and random device id.
Settings -> Playback access token headers -> Random device id

**Comment by crackededed** [comment]
> That fixed it, turning off adblock worked by itself. Thanks, and if you could, would you please explain why this happens, why turning off adblock solved it and what effect the random device id has? I'm really curious.

when the adblock is on ttv lol will get the playback access token for us. so i don't think we can control what headers they use. when off we get this ourselves instead with our own headers. when device id header is empty you will get the commercial break in progress screen. twitch website uses a random id so i've made it the default option in case the id used stops working.

**Comment by RoonMoonlight** [comment]
TTV LOL is currently broken so it no longer works as intended
