### ISSUE TITLE
Ads with Turbo

### ISSUE THREAD

**Issue by Osahashi** [crackededed/Xtra#183]
I'm getting ads when I join a stream and reload the stream, I'm a Turbo user, is there any setting I need to change? 

I already disabled the adblocker and disabled random device id, GQL token.

Do I need to set the device admin for the app? I'm confused about that, because why should the app need that?

**Comment by crackededed** [comment]
the admin thing is for locking the screen after sleep timer is done. make sure you have a gql token: Settings -> Api settings -> Tokens -> GQL token. if you do and it doesn't work then there's probably some other checks that would need to be added to xtra
