### ISSUE TITLE
Playing VODS is broken

### ISSUE THREAD

**Issue by imBigo** [crackededed/Xtra#189]
Playing vods does not work currently.

**Comment by crackededed** [comment]
update the app

**Comment by Disqu3-mirOir-qt** [comment]
thank for fast update

**Comment by imBigo** [comment]
I can't update, the apk tells me the app seems invalid. I'm on a Pixel 5 currently running f-droid latest build

**Comment by BlanXyz** [comment]
> I can't update, the apk tells me the app seems invalid. I'm on a Pixel 5 currently running f-droid latest build.
> (Update and fix worked for my friend)

Fdroid signs Apk's with their own keys therefore they are not cross-compatible. U will either have to wait for Fdroid to build and update their repository or Uninstall the Fdroid version first.

**Comment by imBigo** [comment]
> > I can't update, the apk tells me the app seems invalid. I'm on a Pixel 5 currently running f-droid latest build.
> > (Update and fix worked for my friend)
> 
> Fdroid signs Apk's with their own keys therefore they are not cross-compatible. U will either have to wait for Fdroid to build and update their repository or Uninstall the Fdroid version first.

Thanks
