### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by dandeliontea** [crackededed/Xtra#19]
Any plans to launch app on [F-Droid](https://f-droid.org)? If you don't mind the idea, I could help with providing the relevant information to their submission queue.

**Comment by crackededed** [comment]
yeah sure you can submit it

**Comment by dandeliontea** [comment]
Done! Here's [the link](https://gitlab.com/fdroid/rfp/-/issues/2025), so you can keep up with the packaging progress if you're interested.

**Comment by izk8** [comment]
5/6 steps complete. LMK if I can do anything to help this along

**Comment by izk8** [comment]
Is there anything that needs to be done to keep the package up to date as the package progresses?

**Comment by linsui** [comment]
Which tag should we picked? the latest several tags has the same version and version code.

**Comment by linsui** [comment]
Thanks! Please do bump the version code when you want F-Droid pick the new version.

**Comment by linsui** [comment]
> But here both the original & fork app ID are same : com.github.andreyasadchy.xtra

Yes, they have the same ID. It's not changed when the repo is forked so it's the same. Since the origin repo has been archived and this fork is recommanded in the readme of the origin repo I see no problem.

**Comment by licaon-kter** [comment]
@andsofine https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10995#note_992121257

**Comment by crackededed** [comment]
the builds on fdroid are all from different branches. can you check for updates on the "latest" tag only?

**Comment by licaon-kter** [comment]
Anything against having actual tags from time to time? Say 0.8 and 0.9 and etc

**Comment by linsui** [comment]
I thought we can do that. I didn't try this before but it should work since we use the commit hash.

**Comment by crackededed** [comment]
i made a "v2.0.4" tag. is that going to work?

**Comment by licaon-kter** [comment]
This version was picked before (https://gitlab.com/fdroid/fdroiddata/-/commit/9380f925cb795a7872e64339c1c3b74e73804f1f)  but do keep tagging in the future :)

**Comment by licaon-kter** [comment]
Think this can be closed, right?
