### ISSUE TITLE
[New Feature Request] Auto-update setting

### ISSUE THREAD

**Issue by TheMercenary333** [crackededed/Xtra#190]
It would be great to add an option to auto-update or manually download available updates.

**Comment by crackededed** [comment]
yes. but i'm not sure how the app could check what the latest version number is.

**Comment by imBigo** [comment]
> yes. but i'm not sure how the app could check what the latest version number is.

If it's not possible then would it be possible to add a link to the latest release? (Link would always be the same I believe : https://github.com/crackededed/Xtra/releases/tag/latest)

**Comment by crackededed** [comment]
i guess a text file would work. maybe could even download and install the apk inside the app from https://github.com/crackededed/Xtra/releases/download/latest/app-release.apk

**Comment by imBigo** [comment]
> i guess a text file would work. maybe could even download and install the apk inside the app from https://github.com/crackededed/Xtra/releases/download/latest/app-release.apk

Indeed, you could maybe run some sort of hash (sha256, md5, etc.) on the apk file to verify if the apk is different from the current version

**Comment by Sytten** [comment]
If the releases on GitHub start using the version of the app you can easily fetch it from the app and compare with the app version.

**Comment by crackededed** [comment]
#479
