### ISSUE TITLE
[Feature request] Add methods to bypass Twitch VOD Limit

### ISSUE THREAD

**Issue by RoonMoonlight** [crackededed/Xtra#193]
Hello, recently Twitch Korea announced that they are going to drop VOD support this December.

Related article:
https://m.koreatimes.co.kr/pages/article.asp?newsIdx=339599

Can you make feature which allows bypassing VOD limit on certain countries?

**Comment by crackededed** [comment]
the pogu live/twitch recover method would probably work for this. would let us access deleted/sub only vods too

**Comment by crackededed** [comment]
#215
