### ISSUE TITLE
Video is lagging on source quality 

### ISSUE THREAD

**Issue by App1erush** [crackededed/Xtra#197]
Phone: Xiaomi Redmi note 8 pro
Latest version 
When I switch to the source quality (1080p60 specifically) - the stream starts to lag, fps seems to drop to 15 or so. Doesn't happen on other stream settings (720p60, 1440p60).

**Comment by App1erush** [comment]
Just checked the old exoplayer version - works just fine for me

**Comment by crackededed** [comment]
latest version has a new setting that should fix low fps when enabled
Settings -> Use first media decoder only

**Comment by crackededed** [comment]
fixed in exoplayer 2.18.3
