### ISSUE TITLE
vods only for subs

### ISSUE THREAD

**Issue by TidalMist** [crackededed/Xtra#198]
Recently it became possible to watch vods only for subs without a sub, but only the maximum quality, and to watch in another you need to download and choose the quality. 
is it possible to add quality selection(and audio_only) without downloading? I think when watching in max quality the m3u8 link is taken as when downloading.
big thx

**Comment by crackededed** [comment]
yes it's possible. i'm just not sure how to insert the qualities manually since they don't come with the m3u8 like usually

**Comment by crackededed** [comment]
yeah i know how to get the urls but idk how to get exoplayer to playback the other qualities

**Comment by Disqu3-mirOir-qt** [comment]
only available to exoplayer2 if not doing error

**Comment by Disqu3-mirOir-qt** [comment]
https://stackoverflow.com/questions/45835562/quality-selector-for-exoplayer-2

**Comment by TidalMist** [comment]
maybe this will help https://gitlab.com/twitchmod/orange-tv/-/tree/main/app/features/vodhunter

**Comment by TidalMist** [comment]
Big thx!
If you have time, is it possible to save the time position when switching quality

**Comment by crackededed** [comment]
> Big thx! If you have time, is it possible to save the time position when switching quality

should work now
