### ISSUE TITLE
Are those total permission giving normal?

### ISSUE THREAD

**Issue by racalle** [crackededed/Xtra#199]
Hi, are all this permission needed in order to use Xtra? Please clarify and thx:

![Screenshot_20221208-125119_Trebuchet](https://user-images.githubusercontent.com/72765264/206440695-c1ec1b2c-b04a-4fe1-af33-78d63bf05a4e.png)

**Comment by crackededed** [comment]
they are used for chat commands. commands need to be done through the api now instead of irc so these permissions are needed for that

**Comment by racalle** [comment]
OK, thank you for the information.
