### ISSUE TITLE
Feature Request; video proxy URL

### ISSUE THREAD

**Issue by Sokoloft** [crackededed/Xtra#202]
Hello,

I use [luminous-ttv](https://github.com/AlyoshaVasilieva/luminous-ttv) as my video proxy for the m3u8 request. It'd be nice to have the ability to enter in the URL to the hosted instance in the settings. Currently only ttv lol api is available and isn't working. :(

**Comment by crackededed** [comment]
added a setting for this. i tried it with `https://eu.luminous.dev/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true` and it seems to work

**Comment by Sokoloft** [comment]
> added a setting for this. i tried it with `https://eu.luminous.dev/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true` and it seems to work

Nice. However will the end user be able to add their own instance URL of luminous-ttv running on their own network? Say I have it running on my network at 192.168.108.307:9595. 

As well as let me know what branch its pushed to or if its master. I'll try and build and test it. Assuming I can just use android studio, shouldn't be hard.

**Comment by Sokoloft** [comment]
Awesome, latest release seems to be working fine. Just had to change up the URL to the one you had. Changing playlist to live and removing the m3u8. Thank you 👍
