### ISSUE TITLE
"Unsupported browser"

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [crackededed/Xtra#209]
Logins being blocked like they are on librewolf

**Comment by neurodiverseEsoteric** [comment]
(login by browser still works, for now, though)

**Comment by neurodiverseEsoteric** [comment]
but live channels remains empty

**Comment by crackededed** [comment]
> but live channels remains empty

which app version?

**Comment by neurodiverseEsoteric** [comment]
2.10.1

**Comment by neurodiverseEsoteric** [comment]
Oh, so it's fixed in 2.10.2 ...?
