### ISSUE TITLE
Video delay

### ISSUE THREAD

**Issue by Elliotanderson97** [crackededed/Xtra#214]
There's like 15 seconds delay , also animated emotes work but in slowmotion. i have the latest version btw

**Comment by crackededed** [comment]
you probably need to disable stream proxy in settings for lower delay

**Comment by Elliotanderson97** [comment]
Yes, its disabled

**Comment by Sytten** [comment]
But it will show ads no? It might be worth writing s small guide on the readme to explain the different methods to avoid ads. I switch to the luminous proxy and it seems to be working fine.

**Comment by jojobozo** [comment]
> But it will show ads no? It might be worth writing s small guide on the readme to explain the different methods to avoid ads. I switch to the luminous proxy and it seems to be working fine.

What's the URL for this proxy?

**Comment by crackededed** [comment]
> > But it will show ads no? It might be worth writing s small guide on the readme to explain the different methods to avoid ads. I switch to the luminous proxy and it seems to be working fine.
> 
> What's the URL for this proxy?

change the custom proxy setting to this: `https://eu.luminous.dev/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true`

**Comment by jojobozo** [comment]
> 

Thanks
