### ISSUE TITLE
vod for south korea region

### ISSUE THREAD

**Issue by pepperdiner2** [crackededed/Xtra#215]
some times ago, twich made a decision to remove the vod feature for users in south korea.
it would be very much appreciated if there was a way to watch vod in the app for SK users.

**Comment by pepperdiner2** [comment]
![Screenshot_20230112-071336](https://user-images.githubusercontent.com/97860635/211929391-ebef9d1b-8b7d-42ae-b0ae-fbcda20b6094.png)

for reference, every channel's vod page looks like this for us.

**Comment by crackededed** [comment]
can you open these links or do they give an error?

https://dgeft87wbj63p.cloudfront.net/805b8d805688069c18c4_pgl_dota2_40320976392_1673508923/chunked/index-dvr.m3u8

https://dgeft87wbj63p.cloudfront.net/805b8d805688069c18c4_pgl_dota2_40320976392_1673508923/chunked/1000.ts

**Comment by pepperdiner2** [comment]
both link gave me this error


403 ERROR
The request could not be satisfied.
The Amazon CloudFront distribution is configured to block access from your country. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

**Comment by pepperdiner2** [comment]
this might be obvious but vpn restores the vod

**Comment by crackededed** [comment]
that seems to be the only solution right now

**Comment by RoonMoonlight** [comment]
...

**Comment by pepperdiner2** [comment]
welp, thx for taking a look at it
