### ISSUE TITLE
I keep getting "Player error. Retrying."

### ISSUE THREAD

**Issue by imBigo** [crackededed/Xtra#223]
I'm using `https://eu.luminous.dev/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true` as a adblock.
Also here's the rest of the token settings:
![Screenshot_20230131-221359.png](https://user-images.githubusercontent.com/54672433/215936601-f09e99d2-66b1-4a8f-bd2c-372e2d27a566.png)

**Comment by crackededed** [comment]
fixed. also these settings don't do anything when you are using a proxy since the proxy gets the token and not us
