### ISSUE TITLE
Ttv Lol is offline, disable adblock to view streams in the meantime

### ISSUE THREAD

**Issue by TizioTiburzio** [crackededed/Xtra#224]
Since yesterday update ttv lol does not work anymore
![Screenshot_20230201-111316754_1](https://user-images.githubusercontent.com/102532939/216014725-8a59fbf4-0c5e-48fe-9deb-dfc0bafffe6e.jpg)

**Comment by TizioTiburzio** [comment]
I tried with 2 my devices with different versions of android, both with yesterday and today releases but they shown the same issue

**Comment by crackededed** [comment]
fixed
