### ISSUE TITLE
Switching to Audio-Only will sometimes pause the player.

### ISSUE THREAD

**Issue by imBigo** [crackededed/Xtra#227]
I managed to get audio only working with luminous (many thanks @crackededed) however like the title says on my second try at it it would just stop when switching to Audio-Only and not show the play button unless I switch back to a different quality (that also has video).
Is the play/pause button not on when there's no video? If so could it be possible to have it be shown?

**Comment by imBigo** [comment]
Also it seems I can't play audio in background at all and automatically pauses. (When selecting audio only).

Also I have noticed this for a while now but I don't see the media player in the notifications which would be awesome to have (if possible)
I think you're not using the usual media audio since I can play music over the streams which you can't usually do.

**Comment by crackededed** [comment]
seems like the play button isn't showing sometimes when it should. you can turn on the play/pause button in the settings to make sure it's always visible. if the player is paused or buffering when switching to audio player it will start as paused so make sure it is playing before switching.

> I don't see the media player in the notifications

make sure notifications are enabled for xtra

> I can play music over the streams which you can't usually do.

this is because the app doesn't use audio focus currently

**Comment by imBigo** [comment]
> seems like the play button isn't showing sometimes when it should. you can turn on the play/pause button in the settings to make sure it's always visible. if the player is paused or buffering when switching to audio player it will start as paused so make sure it is playing before switching.
Yes I enabled that but for some reason for me switching to Audio-Only (be it by exiting out of the app with the audio-only settings on) or by just using the settings while the stream is playing it just goes blank and sound never comes. I'm not sure if this has something to do with the new luminous update but with the play/pause always shown the player is just not responding for me in audio only

**Comment by crackededed** [comment]
the player works differently now so this is probably fixed
