### ISSUE TITLE
Feature request: vods tab  

### ISSUE THREAD

**Issue by sumsar158** [crackededed/Xtra#23]
if possible a way to get back followed streamers vods tab from the original version or under channels tabs when clicked on a channel a way to save sorting type to past broadcasts ![Screenshot_20220223-114726.jpg](https://user-images.githubusercontent.com/23150537/155302843-3929c118-4b25-4dfc-9e16-3f1892d6bb43.jpg)

**Comment by sumsar158** [comment]
![Screenshot_20220223-153234_Xtra](https://user-images.githubusercontent.com/23150537/155329495-da5933c4-f649-4c4a-ae10-1aedcf9d614b.jpg)
![Screenshot_20220223-153207_Xtra](https://user-images.githubusercontent.com/23150537/155329508-8370fbd0-b970-4d99-be74-bab15f09c367.jpg)

**Comment by sumsar158** [comment]
![Screenshot_20220223-153359_Xtra](https://user-images.githubusercontent.com/23150537/155329668-41ecc578-a652-457f-99d8-763a6f0936b1.jpg)

**Comment by crackededed** [comment]
followed vods require logging into gql. it's not possible in the app right now. if it becomes a thing i can add this

**Comment by sumsar158** [comment]
> followed vods require logging into gql. it's not possible in the app right now. if it becomes a thing i can add this

Idk if it's relevant but there is Smart twitch tv for Android tvs and somehow they still have the function, latest changelog said that it required users to add authorization key...mby it helps

**Comment by crackededed** [comment]
added
