### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by warriorcat72** [crackededed/Xtra#232]
for some reason, the selection button for local or account follow always sticks to the local follow button even though its actually selected to be follow from twitch account

**Comment by crackededed** [comment]
do you have a gql token? you will need one: Settings -> Api settings -> Tokens -> GQL token

**Comment by warriorcat72** [comment]
![Screenshot_2023-02-19-18-31-00-078_com github andreyasadchy xtra](https://user-images.githubusercontent.com/50791430/219945171-5dfffd42-2000-471a-ab3f-f84c9cb03222.jpg)
uhh im now here but, what do i do now?

**Comment by warriorcat72** [comment]
is it gql client id?
