### ISSUE TITLE
Sorting option not working anymore

### ISSUE THREAD

**Issue by Schmongo** [crackededed/Xtra#236]
Hey.

Recently the sorting option in the popular tab isnt working anymore.
Normally it would show different languages to filter but now it says only "nothing here".
Sorting in the games tab still works as usual.

**Comment by crackededed** [comment]
stream tags were updated to use customizable tags because the old ones are getting removed. i don't think there's any way to get a list of these new tags so you have to search for them. games are using the old tags so they are unaffected
