### ISSUE TITLE
The settings are not translated into Russian.

### ISSUE THREAD

**Issue by bamper45** [crackededed/Xtra#24]
![Screenshot_20220224-032909](https://user-images.githubusercontent.com/77186394/155420824-b631c4cc-ca8c-4605-86c6-160ce1403318.jpg)
I do not know a feature or a bug, but I would like a translation into Russian.

**Comment by crackededed** [comment]
the strings i have added haven't been translated yet. i don't speak russian so i'm not going to translate them. [Here's](https://github.com/crackededed/Xtra/blob/master/app/src/main/res/values-ru/strings.xml) the file if you want to do it.

**Comment by bamper45** [comment]
@crackededed Hello, thanks for the reply, I didn't have time.
I don’t understand this at all, but I asked a man and he translated the program. I was given a stings.xml file. Here:
[strings.zip](https://github.com/crackededed/Xtra/files/8155686/strings.zip)

**Comment by crackededed** [comment]
nice thank you
