### ISSUE TITLE
[Feature Request] Stream Link Creator / Share Button 

### ISSUE THREAD

**Issue by TheMercenary333** [crackededed/Xtra#253]
Is it possible to add a system where we can copy links to streams and vods? On the other hand, can a system be added where we can copy the links and open the relevant streams on Xtra?

**Comment by hellishvictor** [comment]
Yeah, copy the url of clips and vods will be a great implementation.

**Comment by crackededed** [comment]
added

**Comment by hellishvictor** [comment]
Thank you, you're god!

**Comment by hellishvictor** [comment]
I only see the button for share the channels. Where is for the video or clips?

**Comment by crackededed** [comment]
there's a menu button on videos and clips before you open them

**Comment by hellishvictor** [comment]
I can't find it on Android 12. Please, unload a screenshot.

**Comment by crackededed** [comment]
![Screenshot_20240927_215556](https://github.com/user-attachments/assets/cdc17001-ac22-463f-9494-ff58fc4f0c42)

**Comment by hellishvictor** [comment]
Thank you very much, you're god!
