### ISSUE TITLE
Going from audio back to the app resets video

### ISSUE THREAD

**Issue by Sytten** [crackededed/Xtra#256]
Sometimes, when you exit the app, put it audio only in the background and you come back in the app, it will reset the video position back to the beginning.

This doesn't seem to always happen, so it's probably an edge case. The video position is still correctly set when you in the channel tab so its only the player that doesn't pick it up.

**Comment by crackededed** [comment]
seems like closing the audio notification will reset the position as well

**Comment by Sytten** [comment]
I am happy to help you on that, I will try to do the app setup this weekend

**Comment by Sytten** [comment]
I did a bit of digging, it doesn't happen on all videos.
So far what I see is: `VideoPlayerViewModel->onResume->changeQuality->player?.seekTo`
On some videos thats fine, but on some the seek works but then a second seek seems to reset the position.

**Comment by Sytten** [comment]
It looks like a race condition between two calls to `seekTo`:
https://github.com/crackededed/Xtra/blob/9547111e91936e32f9bad2a3d7f600efdfdcdb7b/app/src/main/java/com/github/andreyasadchy/xtra/ui/player/HlsPlayerViewModel.kt#L98
and
https://github.com/crackededed/Xtra/blob/9547111e91936e32f9bad2a3d7f600efdfdcdb7b/app/src/main/java/com/github/andreyasadchy/xtra/ui/player/video/VideoPlayerViewModel.kt#L152

When debugging the first seek is called with 0 and the second with the stored position. Sometimes it looks like the seek to 0 wins, but this doesn't happen for all videos.

**Comment by Sytten** [comment]
Ha I found the bug, its because of these lines
https://github.com/crackededed/Xtra/blob/9547111e91936e32f9bad2a3d7f600efdfdcdb7b/app/src/main/java/com/github/andreyasadchy/xtra/ui/player/HlsPlayerViewModel.kt#L52-L56

They reset the player which reset the playbackPosition without seeking to the previous position
