### ISSUE TITLE
Videos page missing on latest release

### ISSUE THREAD

**Issue by Sytten** [crackededed/Xtra#265]
Seems like the page is missing in the latest release? Maybe I need to reset something.

**Comment by crackededed** [comment]
which page? followed videos? do you have a GQL token? check: Settings -> Api settings -> Tokens -> GQL token

**Comment by Sytten** [comment]
Ha I dont, I have a helix token. I had trouble in log-in so I used the browser way.

**Comment by Sytten** [comment]
Tried log-in in the app again and it just falls in an infinite loading loop. So likely a query is in error or not loading properly, will have to debug.

I am not familiar with the helix vs graphql system. And I imagine the choice between custom query vs query is that you tweaked some fields to display more info?

**Comment by crackededed** [comment]
gql login isn't working right now (at least with 2fa). you can change this setting to only log in to helix: Settings -> Api settings -> Tokens -> Get token for selected apis -> Helix

> helix vs graphql

a lot of things are available only from gql. like followed videos

> custom query vs query

the normal queries are the same as what the website uses. problem is that when they get updated the old queries will eventually stop working. so the app needs to be updated to keep up with this. custom queries don't have this problem but some things like following doesn't work through them.

**Comment by Sytten** [comment]
Yeah works with only the helix token, but like you said the following videos are not available. That's quite interesting I understand the difference. Basically using the undocumented api of possible then fall back to official api.

**Comment by crackededed** [comment]
#266
