### ISSUE TITLE
Graphql auth is broken

### ISSUE THREAD

**Issue by Sytten** [crackededed/Xtra#271]
Did some digging and it looks like the oauth redirect url is invalid. This is very important for the oauth flow to work correctly.
The web application seems to use a newer passport method to login the user, we might have to switch to it.
I will dig into the mobile app to see what they do there.

```
https:\/\/www.twitch.tv\/passport-callback?error=redirect_mismatch\u0026error_description=Parameter\u002bredirect_uri\u002bdoes\u002bnot\u002bmatch\u002bregistered\u002bURI
```

**Comment by Sytten** [comment]
For reference the form method is what is coded in youtube-dl: https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/twitch.py
From there we could then grab the token for the helix API too, but it would be a second step instead of being the first step like it is right now.

**Comment by Sytten** [comment]
Ok so it looks like the oauth client of the android app (`kd1unb4b3q4t58fwlpcbzcbnm76a8fp`) still works with the current redirect URI: `https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=kd1unb4b3q4t58fwlpcbzcbnm76a8fp&redirect_uri=https://www.twitch.tv&scope=`.
For the time being I will revert the changes made a while back to have those two tokens checked and only keep the android one. Though I would put as a larger task on your radar to move to the passport form call instead.

**Comment by Sytten** [comment]
Haha, I continued digging and I found the new redirect uri for the client `kimne78kx3ncx6brgo4mv6wki5h1ko` (web), it's `https://www.twitch.tv/passport-callback`. I will still cleanup a bit that code it's a real mess.

**Comment by Sytten** [comment]
Hum @crackededed I am scanning the codebase and I am seeing some places using the token 2 and some places using the token 1. Was that intentional (like the android client has more permissions or something) or just a work-in-progress transfer that never was completed?

If that is the later, I would do:
- Centralize the auth in one place instead of passing it around everywhere
- Use a concept on client id / token fallback instead of 1 and 2
- Make it transparent for the requester of client and token
- Change the setting so we just have a concept of graphql clients in order of preference (which are an id and a redirect URL)

If we need to maintain the difference, I would still:
- Centralize the auth in one place instead of passing it around everywhere
- Call it web client and android client to make the distinction clear
- Make it so the calling code does something like `GraphqlAuth::get_auth(WEB)`
- Make it clear in the settings that its web and android clients

I will make the changes based on your answer.

**Comment by crackededed** [comment]
> Haha, I continued digging and I found the new redirect uri for the client `kimne78kx3ncx6brgo4mv6wki5h1ko` (web), it's `https://www.twitch.tv/passport-callback`. I will still cleanup a bit that code it's a real mess.

ok nice. i just made a quick fix for this

**Comment by crackededed** [comment]
when using the web client id there's a thing called "client integrity" which needs to be passed when doing some things like logging in, following users, claiming channel point bonuses. when using the mobile client id it's not needed. so gql token 2/mobile id token is used to bypass client integrity.

**Comment by crackededed** [comment]
i think the reason why id.twitch.tv is used for login is because after logging in you get an url with access token in it and i believe you don't get that if you use like twitch.tv/login. the access token needs to be in the url because i don't think there's any other way to get it from webview

**Comment by Sytten** [comment]
> when using the web client id there's a thing called "client integrity" which needs to be passed when doing some things like logging in, following users, claiming channel point bonuses. when using the mobile client id it's not needed. so gql token 2/mobile id token is used to bypass client integrity.

Can we move all API calls to the mobile token then?

**Comment by Sytten** [comment]
> i think the reason why id.twitch.tv is used for login is because after logging in you get an url with access token in it and i believe you don't get that if you use like twitch.tv/login. the access token needs to be in the url because i don't think there's any other way to get it from webview
> 
> > move to the passport form call
> 
> so with web client id we can't do this using okhttp because client integrity can't be passed. the webview passes it (atleast above android 5. maybe android 6 doesn't work also) but we probably can't get the token because it's not in the url

You do get the token, I reversed it and it's quick simple since you basically don't have to deal with the webview. You have your own UI and you do 4 steps:
1. Get integrity token
2. POST username and passport and integrity in body
3. Get a second integrity
4. POST 2fa, integrity and code of step 2 in body

Then you get the access token. But like I mentioned then its a pain to get the helix token since that is a "real" oauth flow that is needed so you would need to inject the proper cookies in a webview.

So scrap that idea, lets continue using the current method but I will document that. Lets focus on centralizing auth so its simpler to modify if twitch decide to change.

If possible we should eliminate the web client and use the android client everywhere instead.

**Comment by Sytten** [comment]
Couple other things I thought about:

- The browser login alternate method only fetches the helix token for the same reason that I mentioned in the previous comment (missing webview cookies). This could be OK since its a backup but not ideal.
- You can interact further than URL with a webview if you inject some JS code into it prior to loading the URL. All the major app (like facebook) do that for tracking but its the same method if we want to do some custom stuff directly in the DOM.
- Since you only need to approve the oauth helix app once for the flow (it redirects automatically after that), we could in theory do the gql login with POST, inject the token in a webview, show it if it is the first app login, retrieve the helix token. But still think helix is preferable over gql since it breaks less often and its a graceful degradation. So still not a good idea...

**Comment by crackededed** [comment]
> Can we move all API calls to the mobile token then?

yes. should we? i think if any changes are made in the future it would be to restrict the client ids that bypass client integrity. if something like that happens we probably don't want to be logged in using only the mobile token. i believe the web token would be a reliable backup in this case.

> Get integrity token

yes you can get an integrity token but if it is created in the app (not using webview) it will not work when you try to use it. at least when i last checked.

> You can interact further than URL with a webview if you inject some JS code into it prior to loading the URL. All the major app (like facebook) do that for tracking but its the same method if we want to do some custom stuff directly in the DOM.

using webview if we can log in to twitch.tv/login and get the token from cookie i think this would be a very stable solution.

**Comment by Sytten** [comment]
We should build it in a way that we can add whatever token is required in the future with minimal changes.

They might require an integrity token for the mobile client, but I then expect them to also provide a way to create one in an api fashion because their mobile app doesn't use a webview for login (I did some reverse engineering on it yesterday). They use a form and an api call to create the integrity token.

I have an hunch that it might have failed because it was missing other headers that the official client uses to try to soft block unofficial clients. Kinda of a fingerprint that needs to match for the integrity token to work.

I will first check to refactor the auth usage in the various services then I can check to refactor how we get the token for sure.

I like the system of fallbacks in general and partial degradation so I will check what we can do.

**Comment by theridon** [comment]
Yeah, I've been unable to log into the app recently.

**Comment by crackededed** [comment]
> Yeah, I've been unable to log into the app recently.

you need to reinstall or change this setting to log in:
Settings -> Api settings -> Tokens -> GQL redirect url -> https://www.twitch.tv/passport-callback

**Comment by crackededed** [comment]
nvm now the second gql login doesn't work

**Comment by crackededed** [comment]
fixed
