### ISSUE TITLE
Compact layout no longer shows viewcount and uptime

### ISSUE THREAD

**Issue by SebiderSushi** [crackededed/Xtra#274]
App version: `2.17.2`
Downloaded from: F-Droid

In the last F-Droid upgrade from 2.16.2 to 2.17.2 it appears that the viewcount and uptime elements where moved from the stream title / category / channel name card to the bottom the stream thumbnail. Since they aren't moved / replicated in the compact layout they are missing on screen.

**Comment by crackededed** [comment]
fixed

**Comment by SebiderSushi** [comment]
Thanks for the quick fix!
