### ISSUE TITLE
Stream has ended (Xtra no longer loading streams)

### ISSUE THREAD

**Issue by beerninja** [crackededed/Xtra#276]
Worked a couple days ago when I tried it and now the streams connect to chat but don't load the actual stream.  Just have the loading icon and eventually it gives up and says stream ended even though it's not ended.

**Comment by crackededed** [comment]
using the android 4 version?

**Comment by beerninja** [comment]
> using the android 4 version?

I'm on the latest version from fdroid, 2.17.4.  running on an ancient android 7 tablet I have sitting on a night stand so I can watch streams sometimes :-)

I got the error in the title yesterday and then it somehow logged me out.  Streams play fine when I'm logged out but when I attempt to log in the white loading animations just spins around forever and it doesn't load or log in.  I have 2FA turned on and it seemed to log in successfully but won't load.  After I close the app and load it back in it stays logged out.

**Comment by crackededed** [comment]
you need to reinstall or change this setting to log in:
Settings -> Api settings -> Tokens -> GQL redirect url -> https://www.twitch.tv/passport-callback

**Comment by beerninja** [comment]
that worked, thanks!  Love your app, keep up the great work
