### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by dzkfzn** [crackededed/Xtra#277]
After successfully login, the screen went blank

**Comment by pdavid345** [comment]
Same issue, pixel 6, android 13, Version 2.11.0

**Comment by pdavid345** [comment]
@dzkfzn solution from subreddit:

it should work on a fresh install. if updating from an older version you need to change this setting manually:
Settings -> Api settings -> Tokens -> GQL redirect url -> https://www.twitch.tv/passport-callback

**Comment by dzkfzn** [comment]
> @dzkfzn solution from subreddit:
> 
> it should work on a fresh install. if updating from an older version you need to change this setting manually:
> Settings -> Api settings -> Tokens -> GQL redirect url -> https://www.twitch.tv/passport-callback

Thank you so much, it works
