### ISSUE TITLE
ISSUE: Crash when opening a stream on API16 variant

### ISSUE THREAD

**Issue by MikaelaMuller** [crackededed/Xtra#280]
Device specifications
https://m.gsmarena.com/samsung_galaxy_tab_4_7_0_3g-6250.php

How to replicate
1: Install app
2: Log in
3: Watch any stream

Logcat:
[XTRA-API16txt.txt](https://github.com/crackededed/Xtra/files/11405582/XTRA-API16txt.txt)

![Screenshot_2023-05-05-18-55-46](https://user-images.githubusercontent.com/91151184/236441523-2782c801-725c-40eb-9deb-63c0c91eb319.png)
![Screenshot_2023-05-05-18-55-18](https://user-images.githubusercontent.com/91151184/236441534-8f2ab27b-a02c-4de6-b104-cd858214fbb5.png)

**Comment by crackededed** [comment]
fixed

**Comment by MikaelaMuller** [comment]
> fixed

Thanks a lot! Goated dev frfr
