### ISSUE TITLE
Chat in VOD

### ISSUE THREAD

**Issue by nottsynyaf** [crackededed/Xtra#281]
The chat replay is suddenly stopping in the VODs. I counted and it appears that it stops when the 50th message is sent.

**Comment by crackededed** [comment]
should work on the latest version

**Comment by Andmyaxe90** [comment]
I have the same issue. Version 2.17.5 installed from F-Droid. Installing from APK downloaded from Github shows a "Package appears to be corrupt." error. Android 7 on Samsung Galaxy J7.

**Comment by crackededed** [comment]
you have to uninstall the f-droid version or wait for an update

**Comment by LukasThyWalls** [comment]
In my end, it seems fixed in 2.17.7 from f-droid.

I think this can be closed.
