### ISSUE TITLE
[fr] copy VOD URLs?

### ISSUE THREAD

**Issue by throwaway242685** [crackededed/Xtra#282]
can you please implement an option to copy VOD URLs?

**Comment by hellishvictor** [comment]
And also for the clips. Cheers.

**Comment by nameless326** [comment]
yes, please allow us to copy the URL of channels and their VODs/clips :(

**Comment by useless642** [comment]
@crackededed can we at least get an option to copy channel URLs? :(

**Comment by crackededed** [comment]
#253
