### ISSUE TITLE
"Followers" channel emotes from Twitch are not correctly refreshed when changing channels

### ISSUE THREAD

**Issue by LukasThyWalls** [crackededed/Xtra#285]
Hello.

I just realised that something weird is happening with the "followers" channel Twitch emotes, like they aren't be refreshed correctly when changing channels, but i don't found a properly way to test or find what is exactly happening as there are some variables that i can't figure out well, so i tried everything i could.

I tested in two different mobile phones, both of them using **Xtra 2.17.7** with different accounts, having a little different behaviour as explained below.

**Steps to reproduce**

- Go to a channel (offline or online)
- Open chat
- Look Twitch Emotes
- Go to other channel
- Open chat
- Look Twitch Emotes (Go to Step 4)

**Actual Behaviour**

(✔️ seems correct, ❌ incorrect behaviour)

In mobile phone 1, with an account with no channel subscriptions:

- First Channel: It loads and shows the ones there are, normally if it's a followed channel the only available ones are the ones for followers to use in that channel ✔️.
- Next Channels: It shows again the followed emotes (or none) from the first channel, and nothing from the actual channel ❌ .

Since then that happens with every channel it tried, unless i exit completely the app and come back later, and load other different channel with other followed emotes. 

In mobile phone 2, with an account with a subscription and emotes from its channel itself:

- First Channel: It shows the emotes from its own channel ✔️ (included the emotes for followers from its channel ✔️), the shared emotes from the channel subscribed ✔️, and the followed emotes from the actual channel ✔️. 
- Next Channels: Maintained everything, like in the phone 1, including the followed emotes from the other channel ❌.

- IF the first channel is the same as the subscribed one: It shows the emotes from its own channel ✔️ (included the emotes for followers from its channel ✔️), the shared emotes ✔️ and the followed emotes ✔️ from the channel subscribed.
- Next Channels: It shows the emotes from its own channel ✔️ (included the emotes for followers from its channel ✔️), the shared emotes ✔️ from the channel subscribed but NOT the followed emotes from that channel ✔️ , and NOT the followed emotes from the actual channel ❌.

- IF the first channel is its own channel (with its own emotes): It shows the emotes from its own channel ✔️ (included the emotes for followers from its channel ✔️) and the shared emotes ✔️ from the channel subscribed.
- Next Channels: It shows the emotes from its own channel ✔️ (included the emotes for followers from its channel ✔️), the shared emotes ✔️ from the channel subscribed, and NOT the followed emotes from the actual channel ❌.

**Expected behavior**

From every channel, the emotes appearing in the chat Twitch emotes should be:
- Its own channel emotes (if any), including the emotes to use only by followers there (Official Twitch app does like that).
- Shared emotes from Subscribed channels, but not everywhere the emotes for followers from that channels, as them only should appear if you are in that subscribed channel.
- Emotes for followers, only the ones from the actual channel and only in that channel, not showing them in other channels.

**Notes**

- At least the BTTV emotes for a channel are correctly refreshed, as only appear in the channel configured and disappears in others.

---
Thanks!

**Comment by crackededed** [comment]
do you have a GQL token?
Settings -> Api settings -> Tokens -> GQL token

**Comment by crackededed** [comment]
test the new version as well

**Comment by LukasThyWalls** [comment]
> do you have a GQL token? Settings -> Api settings -> Tokens -> GQL token

_Settings -> Api Settings -> Tokens -> GQL Token_ is empty. Both 2.17.7 and 2.17.8, In _Account id_, _Account login_ and _Helix token_ there is data.

> test the new version as well

I tested 2.17.8 with case mobile phone 1, and the followed channels are refreshed. Although you can see the old emotes briefly changing or appearing when you open the chat emotes of other channel, i don't think it's a big issue.

In case mobile phone 2, i will wait for the F-Droid release.

**Comment by crackededed** [comment]
> you can see the old emotes briefly changing or appearing when you open the chat emotes of other channel

 without gql token we have to wait for chat/irc to give us the emote sets. i don't think this can be made any faster using only helix token

**Comment by crackededed** [comment]
i think this works correctly now

**Comment by LukasThyWalls** [comment]
Yes, i should have update this a while ago, since the GQL Token was fixed it worked.

Thanks.
