### ISSUE TITLE
Crashing when typing in live chat.

### ISSUE THREAD

**Issue by Kxsumi** [crackededed/Xtra#293]
[com.github.andreyasadchy.xtra_2023-05-22T10_30_33.457.log](https://github.com/crackededed/Xtra/files/11532092/com.github.andreyasadchy.xtra_2023-05-22T10_30_33.457.log)

**Comment by Kxsumi** [comment]
Turns out it may have been something with the network I was connected to. I am currently on a different network and it has stopped. Odd though since the normal Twitch app did not have this issue.

**Comment by crackededed** [comment]
i think the problem is that some networks block the IRC ports xtra uses to connect to chat. twitch website and mobile app uses websocket for chat so those are not affected.

**Comment by crackededed** [comment]
there's now a setting to connect using websocket. probably fixes this but would be great if you could try it

**Comment by Kxsumi** [comment]
Alright I'll get back to you!

**Comment by Kxsumi** [comment]
Seems to work on this network. I can check tomorrow morning when I'm on that network again.

**Comment by Kxsumi** [comment]
Fixed with Websocket!
