### ISSUE TITLE
Some streams are not processing the video feed.

### ISSUE THREAD

**Issue by NihilusX** [crackededed/Xtra#295]
A small fraction of streams, maybe like 1/20 I try to watch are not displaying the stream correctly. What comes through is the stream (I can see make out the outlines) overplayed by a mess of green pixels. Quality settings, etc don't seem to fix it. Something fixed it on one stream in the last update or 2, others remain messed up. Also TTV lol sucks lately sadface.

A adding note of it's not just the live stream, VOD will have the same discombobulated pixel output; I can repeat this if there's a way to log it.

**Comment by crackededed** [comment]
probably the device doesn't support the required codecs
