### ISSUE TITLE
Player is not visible in fullscreen or album view (Android 4.1.2).

### ISSUE THREAD

**Issue by et342** [crackededed/Xtra#3]
Hello.

First of all − Thank you for continuing this project. Xtra is really nice.

Just installed a new release and there's a problem:

![resized_photo_2022-01-29_21-16-59](https://user-images.githubusercontent.com/34111964/151669010-35c77631-eb61-41c0-b839-3f4655bc1580.png)

There is sound. Taps and double taps have no effect.
The horizontal black bar seems to be a shadow.

It works fine in portrait view:

![resized_photo_2022-01-29_21-17-03](https://user-images.githubusercontent.com/34111964/151669075-d406e2ac-06fd-402d-93a3-6018809e68ed.png)

The little window view when you minimize the stream works too.

**Comment by crackededed** [comment]
should be fixed now

**Comment by et342** [comment]
It is. Thank you so much!
