### ISSUE TITLE
[Android 12] Audio Only Option Missing

### ISSUE THREAD

**Issue by systemicdream** [crackededed/Xtra#30]
The Audio Only playback option is missing on my Pixel 5 (Android 12) while it is still visible on my Pixel 2 (Android 11). Both are on the most recent version.
Pixel 2
![Screenshot_20220301-180752](https://user-images.githubusercontent.com/37970474/156281341-90a27215-a62a-411d-bfb1-7e3ee91ea4c3.png)
Pixel 5
![Screenshot_20220301-180907](https://user-images.githubusercontent.com/37970474/156281344-a15e3c91-f4f5-4bb1-a7ed-4466263bcf1a.png)

**Comment by crackededed** [comment]
fixed
