### ISSUE TITLE
Twitch changed the API and the adblock proxies don't work anymore

### ISSUE THREAD

**Issue by thinkpad4** [crackededed/Xtra#302]
@crackededed Twitch changed their API to have Client Integrity and kasada bot protection.

**Comment by vinnnyyyyy** [comment]
Unfortunately I'm having the same problem, I've tried all available Proxys, apparently Twitch won...

**Comment by thinkpad4** [comment]
@vinnnyyyyy For now, there are big brains trying to find the cracks in the armor

**Comment by vinnnyyyyy** [comment]
> @vinnnyyyyy For now, there are big brains trying to find the cracks in the armor

I hope someone can solve it, because from what I looked for, apparently it seems to be a difficult problem :(

**Comment by crackededed** [comment]
that's just for the web client id. there's other ids that still work. though seems like we shouid be generating the integrity token inside the app soon

**Comment by shadowstejo** [comment]
Anything anyone could do to help?
kotlin isn't my first language but someone might be good at it ;)
If there would be an entry point or you could say what exactly needs to be addressed first, that might help that someone ;)

**Comment by crackededed** [comment]
latest version should be able to get valid integrity tokens already

**Comment by imBigo** [comment]
> latest version should be able to get valid integrity tokens already

For some reason my streams are not loading, I've got the latest version and everything . Am I doing something wrong? @crackededed

**Comment by Sokoloft** [comment]
> > latest version should be able to get valid integrity tokens already
> 
> For some reason my streams are not loading, I've got the latest version and everything . Am I doing something wrong? @crackededed

Does this pertain to you using a playlist proxy? If so I'm using luminous public and it works just fine. 
Stream proxy = custom url
Custom proxy url = ```https://eu.luminous.dev/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true```

**Comment by imBigo** [comment]
> > > latest version should be able to get valid integrity tokens already
> > 
> > For some reason my streams are not loading, I've got the latest version and everything . Am I doing something wrong? @crackededed
> 
> Does this pertain to you using a playlist proxy? If so I'm using luminous public and it works just fine. 
> Stream proxy = custom url
> Custom proxy url = ```https://eu.luminous.dev/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true```

I was using that and it still wasn't working earlier, it's now working :)

**Comment by imBigo** [comment]
I can watch the stream but now I can't send messages @crackededed 
Here's the error: Error sending message - java.net.SocketException: Socket is closed

**Comment by Sokoloft** [comment]
> I can watch the stream but now I can't send messages @crackededed Here's the error: Error sending message - java.net.SocketException: Socket is closed

Open your own issue request. That does not seem relevant to this issue.

**Comment by MisterSheeple** [comment]
Would it be a good idea to add Luminous as a built in proxying option now that TTV LOL no longer works? Though of course, the long term solution would be to implement ad blocking via HTTP proxy (a la TTV LOL PRO v2)

**Comment by thinkpad4** [comment]
@MisterSheeple `api.ttv.lol` works perfect, you must have something else enabled.

**Comment by MisterSheeple** [comment]
Are you sure? Hasn't worked for me on desktop or mobile for weeks.

**Comment by thinkpad4** [comment]
Yep, works perfect, every single time I use it. And I use it on Xtra every single day, sometimes several times a day.  Works PERFECT.

**Comment by crackededed** [comment]
integrity tokens still work fine i think if they are ever even needed
