### ISSUE TITLE
Player error. Retrying when playing at 1080p60

### ISSUE THREAD

**Issue by cris0899** [crackededed/Xtra#305]
When I try to play a stream at 1080p60 I get Player error. Retrying.
![Screenshot_20230601-140038_Xtra](https://github.com/crackededed/Xtra/assets/96213145/de8a1ebf-f5cb-4c2b-870b-251706541f57)
![Screenshot_20230601-140319_Xtra](https://github.com/crackededed/Xtra/assets/96213145/5c6db686-529b-40a4-bcf5-8b623371d580)

Other resolutions play normally.

**Comment by crackededed** [comment]
do vods work at 1080p60?

**Comment by cris0899** [comment]
> do vods work at 1080p60?

nope, vods are broken too

[cid:eu.faircode.email.36]

**Comment by cris0899** [comment]
nope, vods are broken too
![Screenshot_20230711-160817_Xtra](https://github.com/crackededed/Xtra/assets/96213145/389f9682-eb7f-4a3c-9dad-989da7ce16e4)

**Comment by crackededed** [comment]
i guess the device doesn't support this quality
