### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by warriorcat72** [crackededed/Xtra#308]
sort by past broadcasts in the following tab not working, when sorted by past broadcasts it redirects it to sort by last followed

**Comment by Andmyaxe90** [comment]
I'm having the same issue, both with local and account followed. Last broadcast date also disappeared.

**Comment by crackededed** [comment]
i think it's a temporary issue with api. i just looked at users on the website and in the schedule tab it always says "user hasn't streamed recently".
