### ISSUE TITLE
Stream does not stop playing audio when dismissing popup player or using sleep timer.

### ISSUE THREAD

**Issue by thirashima** [crackededed/Xtra#311]
In both cases, the audio will keep playing in the background until you swipe the notification away.

Steps to reproduce for popup player:
1. Open a stream.
2. Minimize the app, so the popup window appears.
3. Attempt to dismiss the popup player by dragging it to the "X".
4. Audio will keep playing in the background.

Steps to reproduce for sleep timer:
1. Open a stream.
2. Set the sleep timer for X minutes.
3. After X minutes, app will close, but audio will keep playing in background.

**Comment by BIPTOA** [comment]
Also kind of similar (happened roughly around the same time), stream stops when you close screen (it used to still play), you need to enable background playing but then you get this bug. I can't remember which twitch app had similar issue while using  Bluetooth headphones which vere using specific version of by.

**Comment by MonsterNya** [comment]
I confirm the problem, I have the same

**Comment by crackededed** [comment]
should be fixed now
