### ISSUE TITLE
Okay, things have got weird since last update.

### ISSUE THREAD

**Issue by NihilusX** [crackededed/Xtra#314]
A.) Not last published github update, f-droid website app. If same version right now it's one previous. 

B.) Started staying open in memory cache. (I only noticed because I'm on a crappy android old kindle from looks 2011 or 2013 and frequently wipe stuff to clear RAM.

C.) Tonight for some weird ass reason ( no data, cache, etc.) clean the app made me login in to Twitch again seemingly out of nowhere if I'm forcing updates, etc. I wouldn't start ringing bells if literally my last update version was the only staying in cache memory upon exiting.

And to,be clear there's no auto update or anything, I get latest version off f-droid website, no application + update my stuff simply because this tablet is ass and I have to monitor running apps to an almost barebones level.

That's some super weird behavior and it's raising red flags for me. Even if it's malicious on my end it'd be meaningless but from my last update experience there's something wrong. App did not hang in cache before, and surely didn't make me re-sign into twitch at a seemingly random point in time.

Side note: old kindle, running candy5, twrp, etc. No other decent explanation for the changes. OS cannot update, there's nothing system side that'd explain that change.

**Comment by NihilusX** [comment]
If everyone else had to relog for Twitch I'm sure it'd be something, if anything before the app itself I'd think a ttvlol error, breach, etc. before the app. I just don't like the recent memory cache hangout.

**Comment by NihilusX** [comment]
Android is a foreign language to me but I spent years participating, heavily using, / paying for, and inspecting various Windows botnets in my past and is this is nearly identical to such a breach, I'm almost 99% sure I've did a site spoof along these exact parameters from host file editing or browser based redirecting before. All of what just happened to me puts me back in time 14 years when I fucked with malware for money and fun. We can all see the source code for the app though, so what's the issue? It's 1000% not my twitch info phishing lol. This tablet hasn't changed or updated in over 3 years and the twitch account only exists because this crappy tablet can't use an outlook app (even outlook lite is literal rip RAM.) So I'm stuck in a suspicious question, where there's no explanation because I really can't see it being the app unless it's very well disguised or stored via a connection to ttvlol or external "disguise"

**Comment by crackededed** [comment]
> Started staying open in memory cache.

did you open the player and then close the app? or how did you do it? i can't get it to stay open after closing.

> app made me login in to Twitch again

did you get the "your session has expired" message? your tokens are refreshed on launch so they shouldn't expire unless you turned off Validate tokens in settings or changed your password or something
