### ISSUE TITLE
AdBlock in Xtra

### ISSUE THREAD

**Issue by nottsynyaf** [crackededed/Xtra#315]
Is there any way of using adblock in Xtra? I've ran out of options as TTV.LOL and the luminous servers don't seem to work anymore.

**Comment by thinkpad4** [comment]
@nottsynyaf I've tested both `api.ttv.lol` and Luminous servers and they are working flawlessly.

**Comment by nottsynyaf** [comment]
Do I have to change something in the API Settings section? Because only letting the TTV.LOL activated in Stream Proxy or putting a custom URL like luminous is not doing anything for me. Bear in mind I'm not a programmer, I'm just a really curious guy that likes to take care of things by myself haha so a somewhat thorough explanation would really help! Thanks.

**Comment by thinkpad4** [comment]
@nottsynyaf Have you entered Luminous exactly like this?  `https://eu.luminous.dev/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true`

**Comment by nottsynyaf** [comment]
> 

Yes, and it still show ads :/

**Comment by crackededed** [comment]
you can try ttv lol pro proxies now #312
