### ISSUE TITLE
App crashing when I listen with bluetooth

### ISSUE THREAD

**Issue by pepin8** [crackededed/Xtra#317]
In my 6.0.1 android, if I listen to a stream on bluetooth earphones, the whole app crashes, "xtra stopped" message immediatly. Two times it pops up actually, for some reason. However, without bluetooth earphones, just speakers, the app works well.
This happens now, and in the previous version at least (maybe before).
But at some point before, the app worked well with this phone. 

In my 5.0.2 android, I can listen with bluetooth earphones just fine, even in the current version.

**Comment by crackededed** [comment]
install this build: [app-debug.zip](https://github.com/crackededed/Xtra/files/11779764/app-debug.zip)
get logs from when it crashes using adb or an app that can view logs

**Comment by thinkpad4** [comment]
@crackededed Does the app-debug install separate from the normal install?  If not, does installing the normal version overwrite the app-debug version?  I too have the crashing with bluetooth connected and didn't know that was causing it until I saw this post.

**Comment by crackededed** [comment]
> @crackededed Does the app-debug install separate from the normal install? If not, does installing the normal version overwrite the app-debug version? I too have the crashing with bluetooth connected and didn't know that was causing it until I saw this post.

yes it's a separate app

**Comment by thinkpad4** [comment]
Sweet, what simple ad free android app do you recommend to view them or do I just post the log file here?

**Comment by crackededed** [comment]
> what simple ad free android app do you recommend to view them

i don't know. i haven't used an app like that in forever

> Is there a hidden settings backup feature

no but if you are rooted you can copy everything from the data folder

> Where does it store the log?

it doesn't. that's why you need a separate app to view the logs

**Comment by thinkpad4** [comment]
I got it to crash but couldn't find a log, I'll try again tomorrow

**Comment by TheMercenary333** [comment]
https://play.google.com/store/apps/details?id=com.dp.logcatapp You can use this one

**Comment by thinkpad4** [comment]
Where should I send the log file?  I don't wanna post it because it has twitch info in it.

**Comment by crackededed** [comment]
just do it on a fresh install. or post the stack trace only

**Comment by thinkpad4** [comment]
[06-20 19:17:56.221 24903:24903 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.github.andreyasadchy.xtra.debug, PID: 24903
java.lang.IllegalStateException: onLoadChildren sent null list for id androidx.media3.session.MediaLibraryService
	at android.service.media.MediaBrowserService$3.onResultSent(MediaBrowserService.java:473)
	at android.service.media.MediaBrowserService$3.onResultSent(MediaBrowserService.java:469)
	at android.service.media.MediaBrowserService$Result.sendResult(MediaBrowserService.java:131)
	at androidx.media.MediaBrowserServiceCompat$ResultWrapper.sendResult(MediaBrowserServiceCompat.java:1279)
	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$2.onResultSent(MediaBrowserServiceCompat.java:418)
	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$2.onResultSent(MediaBrowserServiceCompat.java:406)
	at androidx.media.MediaBrowserServiceCompat$Result.sendResult(MediaBrowserServiceCompat.java:860)
	at androidx.media3.session.MediaSessionServiceLegacyStub.onLoadChildren(MediaSessionServiceLegacyStub.java:93)
	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21.onLoadChildren(MediaBrowserServiceCompat.java:427)
	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$MediaBrowserServiceApi21.onLoadChildren(MediaBrowserServiceCompat.java:518)
	at android.service.media.MediaBrowserService.performLoadChildren(MediaBrowserService.java:495)
	at android.service.media.MediaBrowserService.addSubscription(MediaBrowserService.java:459)
	at android.service.media.MediaBrowserService.access$400(MediaBrowserService.java:68)
	at android.service.media.MediaBrowserService$ServiceBinder$3.run(MediaBrowserService.java:247)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7230)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by thinkpad4** [comment]
[06-20 19:17:58.166 2638:11956 W/ActivityManager]
Service crashed 2 times, stopping: ServiceRecord{5abfb37 u0 com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.player.PlaybackService}

**Comment by crackededed** [comment]
try this media3 demo and see if it crashes on there as well: [base.zip](https://github.com/crackededed/Xtra/files/11820289/base.zip)

**Comment by thinkpad4** [comment]
What is Media3?  Does this test version of Xtra also install separate?

**Comment by crackededed** [comment]
it's a library used in xtra to playback videos

**Comment by thinkpad4** [comment]
And how do I revert to the normal version if this doesn't work?  Just reinstall the normal app?

**Comment by crackededed** [comment]
it's a demo app for the media3 library. so not xtra. try playing a video on it with a bluetooth device connected and see if it crashes like xtra

**Comment by thinkpad4** [comment]
It won't install, it says there is a Parse error. There was a problem parsing the package

**Comment by crackededed** [comment]
post an issue to [media3 repo](https://github.com/androidx/media). include the first log from above

**Comment by thinkpad4** [comment]
@pepin8 I could use some help here, can you try the steps @crackededed mentioned too?  Posting a issue to Media3 repo says it needs adp bugreport.  I don't know what that is or how to do it.  I'm not skilled in the underhood stuff of Android.

**Comment by crackededed** [comment]
just post it with the log. i think it's enough. and include the android version used

**Comment by thinkpad4** [comment]
Submitted a issue to media3 github, we'll see what they do

**Comment by thinkpad4** [comment]
@crackededed They finally responded https://github.com/androidx/media/issues/489#issuecomment-1667382635

**Comment by crackededed** [comment]
try this apk. it has the latest media3 dev version: [app-debug.zip](https://github.com/crackededed/Xtra/files/12289636/app-debug.zip)

**Comment by thinkpad4** [comment]
Still crashes

**Comment by pepin8** [comment]
Sorry that I didn't follow up the issue. I... may be having time to do the follow up steps, but I'm not sure, sorry. If I can I will, but I doubt I see myself having time. Still thanks for the awesome work btw,

**Comment by crackededed** [comment]
see if this crashes: [app-debug.zip](https://github.com/crackededed/Xtra/files/12537274/app-debug.zip)

**Comment by thinkpad4** [comment]
> see if this crashes: [app-debug.zip](https://github.com/crackededed/Xtra/files/12537274/app-debug.zip)

@crackededed THIS WORKS!!!!   IT WORKS with bluetooth.  No crashing!!!!!!!!!!

**Comment by crackededed** [comment]
added some info to the media3 issue. hopefully they fix it because bundling the modified library with xtra causes some issues like doubling the apk size

**Comment by thinkpad4** [comment]
@crackededed Some positive news  https://github.com/androidx/media/issues/489#issuecomment-1771340532

**Comment by thinkpad4** [comment]
@crackededed More good news https://github.com/androidx/media/issues/489#issuecomment-1772948881

**Comment by crackededed** [comment]
i think the fix is included now

**Comment by KaKi87** [comment]
In which version ?

**Comment by crackededed** [comment]
2.26.2

**Comment by KaKi87** [comment]
Alright, waiting for F-Droid availability to check and report back.

**Comment by thinkpad4** [comment]
IT WORKS PERFECT!!!!!  No issue with bluetooth being connected
