### ISSUE TITLE
Open player when there's no stream available

### ISSUE THREAD

**Issue by hellishvictor** [crackededed/Xtra#320]
When a channel is selected in "Following-Channels", it shows the channel tabs "Videos-Clip-Chat", the header (which dissapear when one of the tabs is selected), and if the channel is offline, there appear the "Open Player" text; selecting this one shows the chat, and on the top is placed the image-on-image window with a "reload" icon as it tries to load the stream.
Now, if the user press "back", the  empty "image-on-image" window remains open on the botton as there's no stream, and so, wouldn't it be better just show the "OFFLINE" text?

Cheers.

**Comment by crackededed** [comment]
if changes are made to the api all channels could be shown offline. in that case i think it's good to have an option to open the player anyway
