### ISSUE TITLE
weird visual issue

### ISSUE THREAD

**Issue by warriorcat72** [crackededed/Xtra#337]
![Screenshot_2023-07-16-13-34-23-063_com github andreyasadchy xtra](https://github.com/crackededed/Xtra/assets/50791430/828fa61c-9a73-444a-9b81-46df368df92f)
For some reason the games categories that are in the vods don't show up

**Comment by crackededed** [comment]
can you link the vod?

**Comment by warriorcat72** [comment]
https://twitch.tv/videos/1872745733
This is the vod

**Comment by warriorcat72** [comment]
https://twitch.tv/videos/1872745733
This is the vod

**Comment by crackededed** [comment]
they don't show up on the website either. there's more vods that have this problem too on that channel. maybe the games were not set correctly. i wonder if they show up correctly when the channel is live

**Comment by Glarxan** [comment]
I can confirm having the same issue. It started around 2 weeks ago(?). Before that, there were no problems. Vast majority of games categories from vod shows as blank.

**Comment by crackededed** [comment]
not an issue with xtra
