### ISSUE TITLE
Feature request: Notification when a channel is live

### ISSUE THREAD

**Issue by hellishvictor** [crackededed/Xtra#338]
Hi, I miss an option to allow the user to be notified when one of the channels on the Following tab is live.
I know that streamelements sends an email about it, but I just follow the channel through Xtra, without a twitch account.
Cheers.

**Comment by skburgart** [comment]
Suggestion: Support https://unifiedpush.org/

**Comment by CrazyWolf13** [comment]
@crackededed  This is a duplicate.

**Comment by crackededed** [comment]
#82
