### ISSUE TITLE
Feature Request: Show the time of the stream.

### ISSUE THREAD

**Issue by hellishvictor** [crackededed/Xtra#340]
Hi, I've noticed that there's no option to show the amount of time that has passed since the stream started, and that would be another great implementation for this **awesome** app.
Cheers.

**Comment by AitoZ** [comment]
You can see the uptime before you open the stream, bottom right on the stream preview.

**Comment by hellishvictor** [comment]
> You can see the uptime before you open the stream, bottom right on the stream preview.

Yes, on the preview are the uptime and the viewers; and so, if on the live stream are the viewers on the bottom center, there should be appear also the uptime live.

**Comment by hellishvictor** [comment]
> You can see the uptime before you open the stream, bottom right on the stream preview.

Yes, on the preview are the uptime and the viewers; and so, if on the live stream are the viewers on the bottom center, there should be also the uptime live.

**Comment by crackededed** [comment]
added

**Comment by TheMercenary333** [comment]
If streamer make raid to another channel, it not working. FYI
