### ISSUE TITLE
ttv.lol is offline

### ISSUE THREAD

**Issue by h-yul** [crackededed/Xtra#344]
![Screenshot_20230802_100151_Xtra](https://github.com/crackededed/Xtra/assets/141195072/a686538d-e2d4-464d-82c9-dcd033ad0803)
How can i fix it?
Suddenly from last night.

**Comment by crackededed** [comment]
you can disable it or try a different stream proxy in settings

**Comment by thinkpad4** [comment]
The Official TTV.LOL has been down for a while now, no sign of it coming back.

**Comment by githubUser01946** [comment]
Where can I find custom url's?

**Comment by crackededed** [comment]
should probably remove ttv lol at this point

**Comment by TheMercenary333** [comment]
If I delete the custom TTV url while setting the proxy. When I select TTV proxy again, the custom link does not come back as preset. Any fix for this?

**Comment by BLACK4585** [comment]
What can we do now? All options from the custom proxy are failing and no playback is possible...

**Comment by thinkpad4** [comment]
@BLACK4585 Custom proxies work perfect

**Comment by BLACK4585** [comment]
Can you give us some?

**Comment by clowncracker** [comment]
> @BLACK4585 Custom proxies work perfect

Any custom proxies you recommend?

**Comment by crackededed** [comment]
ttv lol is now removed
