### ISSUE TITLE
Themes aren't shown right after the last update.

### ISSUE THREAD

**Issue by hellishvictor** [crackededed/Xtra#346]
Hi, after the last update, now the theme UI shows some areas in grey where I used to have them config to grey.

Everything is correct on "Games" section.
![photo_2023-08-03_01-11-29](https://github.com/crackededed/Xtra/assets/34694956/fab63a56-48c1-4e89-9b02-0c06ab6c6fa1)

Here "Sort" is shown in grey (notice that on "Games" is shown correctly, in black)
![photo_2023-08-03_01-11-33](https://github.com/crackededed/Xtra/assets/34694956/d7445778-a01f-4863-994f-ac908d6aa0a3)

On the following, these grey areas used to be shown in black before the last update.
![photo_2023-08-03_01-09-27](https://github.com/crackededed/Xtra/assets/34694956/446c42fb-e47b-4bcd-8638-4230b05e429a)
![photo_2023-08-03_01-09-47](https://github.com/crackededed/Xtra/assets/34694956/d1161e11-82db-4d6d-9848-92bd6d60f735)

Maybe there is something I'm missing, but I haven't modified the settings at all.
Cheers.

**Comment by crackededed** [comment]
what android version is this?

**Comment by hellishvictor** [comment]
Android 12

**Comment by hellishvictor** [comment]
I've updated to the [new version](https://github.com/crackededed/Xtra/releases/tag/latest) and now all is right :)
