### ISSUE TITLE
[Feature] Import/Export settings

### ISSUE THREAD

**Issue by DarrenWarrenV** [crackededed/Xtra#351]
Please, please add this. Xtra after a longer while takes a lot of storage space (emotes probably? I'm not downloading any vods). I'm not rooted, so I don't have access to data folder on system partition. Last time it was 2GB. I have to clean app's storage and then go thru hell with setting everything up again and there are a lot of options to switch + follow streamers locally again... this is so frustrating.

**Comment by crackededed** [comment]
try clearing cache. data folder shouldn't take that much space

**Comment by DarrenWarrenV** [comment]
Cache was only around 70MB If I remember correctly, all the rest was data. I went to app info before clearing

**Comment by crackededed** [comment]
have you downloaded any vods previously? some files might have stayed in the download folder

**Comment by DarrenWarrenV** [comment]
I never, ever download any vods. Xtra is running almost 24/7 on my tablet 🤷 BTW thank you for maintaining this project! There's no alternative to it.

**Comment by crackededed** [comment]
#72
