### ISSUE TITLE
Chat freezing after some time watching a vod

### ISSUE THREAD

**Issue by imBigo** [crackededed/Xtra#355]
After watching a vod for some time the chat will no longer be kept up to date when watching a vod. You can fix it by skipping ahead or backwards.

**Comment by hellishvictor** [comment]
Same here on Android 12

**Comment by TiltedToast** [comment]
Same here on Android 13

**Comment by crackededed** [comment]
i think this is fixed now

**Comment by hellishvictor** [comment]
After of this fix, it happens but on the live streams, not on the VODs.

**Comment by crackededed** [comment]
> After of this fix, it happens but on the live streams, not on the VODs.

i don't think this fix changed any of the live chat code so it shouldn't be related to this. you can try turning on `Connect using WebSocket` in settings

**Comment by hellishvictor** [comment]
Done, let's see how it goes.
