### ISSUE TITLE
Feature request: Video Unmute Support

### ISSUE THREAD

**Issue by hellishvictor** [crackededed/Xtra#360]
Hi, it would be beyond awesome if where possible download videos unmuted, as [TwitchLink](https://github.com/devhotteok/TwitchLink) does (but sadly only for Windows 10/11 users).
Cheers.

**Comment by hellishvictor** [comment]
So it's already implemented? Definelly Xtra is beyond awesome :) Closing.

**Comment by crackededed** [comment]
it's not. what i mean is: do you know of any videos that can be unmuted currently?

**Comment by hellishvictor** [comment]
> last time i checked the unmuted segments stopped working pretty quickly after the vod was muted

The VODs with their unmuted versions are available on Twitch servers for up to 24 hours after the stream has ended.

>do you know of any videos that can be unmuted currently?

Not right now.
