### ISSUE TITLE
Feature request: Save live streams

### ISSUE THREAD

**Issue by hellishvictor** [crackededed/Xtra#363]
Hi, implement the option to save a stream while its live would be another brutal feature for Xtra, definelly. Now some streamers don't release the VODs once it ends, and if they are live while you're sleeping you'll miss it.

Cheers.

**Comment by tuxayo** [comment]
Something that partially addresses this on Linux and Windows: https://github.com/crackededed/twitch-stream-recorder

**Comment by hellishvictor** [comment]
> Something that partially addresses this on Linux and Windows: https://github.com/crackededed/twitch-stream-recorder

On Windows it can be done using only StreamLink and the option --record/output, but not in Xtra when using the smartphone; however, I think that the last time I've downloaded a VOD with Xtra, it don't create a mp4, but lots of .ts files :S Thank you anyway, man.

**Comment by crackededed** [comment]
added

**Comment by hellishvictor** [comment]
You're god!
