### ISSUE TITLE
Support for custom playback speed or external player

### ISSUE THREAD

**Issue by dhananjaipai** [crackededed/Xtra#364]
I don't know how difficult it would be, but would really appreciate support for playback speeds higher than 2x

A way to copy the stream link will also help to open it in another player for example and change the speed from there
An option to launch external player would be super helpful.

**Comment by hellishvictor** [comment]
> A way to copy the stream link 

Feature already requested on #[253](https://github.com/crackededed/Xtra/issues/253).

**Comment by dhananjaipai** [comment]
> > A way to copy the stream link
> 
> Feature already requested on #[253](https://github.com/crackededed/Xtra/issues/253).

Yeah. The main request was to be able to increase the playback speed. Being able to copy stream link is one way of working around the issue by using an external player. A better solution may be to be able to directly support an external player from within the app if possible or to edit the playback speed options to allow more options upto 4x

**Comment by crackededed** [comment]
added more playback speeds
