### ISSUE TITLE
libwebp 0day

### ISSUE THREAD

**Issue by linsui** [crackededed/Xtra#373]
Xtra uses https://github.com/zjupure/GlideWebpDecoder which uses libwebp 1.2.4. We can patch the lib by replacing https://github.com/zjupure/GlideWebpDecoder/tree/master/webp_decoder/src/main/jni/libwebp with https://github.com/webmproject/libwebp/commits/1.2.4.

See https://blog.isosceles.com/the-webp-0day/.

**Comment by crackededed** [comment]
this library is updated now

**Comment by linsui** [comment]
Thanks!
