### ISSUE TITLE
Is Android 14 gonna prevent me from installing Xtra?

### ISSUE THREAD

**Issue by thinkpad4** [crackededed/Xtra#374]
`https://9to5google.com/2023/01/23/android-14-block-install-outdated-apps/`  Initially, Android 14 devices will only block apps that target especially old Android versions. Over time though, the plan is to increase the threshold to Android 6.0 (Marshmallow), with Google having a mechanism to “progressively ramp [it] up.”   Will this be affected cause it says Android 5 and up, will that have to be changed to min 6 and up now?  Just wondering as my S23 might be getting 14 this month or next.  Thanks

**Comment by crackededed** [comment]
it will work. targetSdk is different from minSdk. minSdk can be whatever. targetSdk is android 14 in xtra

**Comment by thinkpad4** [comment]
Thanks for closing it, I forgot to do that
