### ISSUE TITLE
TTV.LOL proxies?

### ISSUE THREAD

**Issue by amenoko** [crackededed/Xtra#375]
Hi! I read that the default proxy setting for blocking ads doesn't work anymore at all, is that true? How do I search for compatible alternative proxies? How do I add them properly? (since there always seem to be extra variables after the domain)

Been looking but found no clear or up to date answers. Sorry if this is a dumb question.

**Comment by AitoZ** [comment]
Read [this](https://github.com/crackededed/Xtra/issues/359#issuecomment-1696021141) and [this](https://github.com/crackededed/Xtra/issues/359#issuecomment-1696631999).

**Comment by amenoko** [comment]
Thanks but that doesn't help me find alternative proxies on my own and adding them to the app. How do I search for them, where do I look for them, and how does the URL format work?

**Comment by amenoko** [comment]
sorry missclick

**Comment by crackededed** [comment]
for Custom proxy url luminous and ttv lol pro v1 proxies will work. you can try using a ttv lol pro v2 proxy in HTTP proxy settings

**Comment by AitoZ** [comment]
In the second **this** on my previous comment I've linked where I got them from, the **Custom proxy url** is easy to use. You only change the URL and keep the rest, for example: `CHANGETHEURLHERE/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true`. I hope it helped.

**Comment by amenoko** [comment]
v2 proxies work better, right? Is the syntax for the URL (like the variables after the domain) different? And is the default setting actually broken?

**Comment by crackededed** [comment]
> v2 proxies work better, right?

maybe. with default settings there's probably no difference. you can try turning on Proxy media playlist if ads are detected in HTTP proxy settings if you see ads

> Is the syntax for the URL (like the variables after the domain) different?

just put host and port in HTTP proxy settings. no need for variables

> is the default setting actually broken?

yes ttv lol doesn't work

**Comment by amenoko** [comment]
hm I see thank you! that clear things up
