### ISSUE TITLE
7tv emotes not appear on Recent / Auto-claim points

### ISSUE THREAD

**Issue by hellishvictor** [crackededed/Xtra#376]
Hi, the 7tv/bttv/ffz emotes no appear on the "Recent" tab, but only the ones from "Twitch".
Please, implement auto-claim for the channel points, as the BetterTTV browser extension does.

Cheers.

**Comment by crackededed** [comment]
channel points auto claim should already work. you can turn on Notify when earning channel points to see if it's working

**Comment by hellishvictor** [comment]
Done, you're god,

**Comment by hellishvictor** [comment]
> Hi, the 7tv/bttv/ffz emotes no appear on the "Recent" tab, but only the ones from "Twitch". 

They do appear, but it seems that not right after of use them in the chat or something.

**Comment by hellishvictor** [comment]
> channel points auto claim should already work. you can turn on Notify when earning channel points to see if it's working

Done :)

> Hi, the 7tv/bttv/ffz emotes no appear on the "Recent" tab, but only the ones from "Twitch". 

They do appear, but it seems that not right after of use them in the chat or something.
