### ISSUE TITLE
Feature request: Can we get the "Videos" tab back on the following page?

### ISSUE THREAD

**Issue by hurrdurr1** [crackededed/Xtra#378]
I know I'm probably super late, as I update very rarely. But I'm missing being able to check VODs of streams that have happened while I was asleep. I live in EU and the afternoons are always super dead because everyone in NA is asleep.

**Comment by crackededed** [comment]
it should work if you have a gql token: Settings -> Api settings -> Tokens -> GQL token. try logging in again if you don't have one

**Comment by hurrdurr1** [comment]
Logging in again worked, thanks.
