### ISSUE TITLE
Spoof X-Forwarded-For not blocking ads

### ISSUE THREAD

**Issue by githubUser01946** [crackededed/Xtra#380]
As ttv.lolno longer works I have been using the proxy in the title but that seems to no longer block ads.

Where can I find alternative addresses?

**Comment by AitoZ** [comment]
Read [this](https://github.com/crackededed/Xtra/issues/359#issuecomment-1696021141) and [this](https://github.com/crackededed/Xtra/issues/359#issuecomment-1696631999).

**Comment by githubUser01946** [comment]
Thanks very much 😀

**Comment by AitoZ** [comment]
You're welcome, remember to close the issue if your problem is resolved.
