### ISSUE TITLE
Issue Won't Install Android 14

### ISSUE THREAD

**Issue by squee666** [crackededed/Xtra#384]
My pixel 6 pro won't install this, had older version installed. Update kept failing.
So uninstalled and tried manually installing APK
Nothing happens I hit install on any APK and that's it screen disappears then nothing happens.

**Comment by crackededed** [comment]
would need a log from adb to know what's wrong

**Comment by squee666** [comment]
[file.txt](https://github.com/crackededed/Xtra/files/13079363/file.txt)
hopefully this helps
successfully install the app via sideloading in adb
also noticing it was causing package installer to crash

**Comment by crackededed** [comment]
i think it's fixed now

**Comment by squee666** [comment]
hmmm tried to update and same result hit update/install and it closes and then trying again crashes package installer

**Comment by crackededed** [comment]
can you send another log? one of the errors should be fixed at least

**Comment by squee666** [comment]
Probably a other day or 2 till I can.
Just got my phone back sent it for a warranty battery replacement since it was free.

Can confirm when it came back on Android 13 instead of 14 the app installed just fine.
Will see if persists later on 14 if not I will log

**Comment by squee666** [comment]
[file.txt](https://github.com/crackededed/Xtra/files/13208723/file.txt)
heres latest adb

**Comment by crackededed** [comment]
still shows this in the log
```
FATAL EXCEPTION: main
Process: com.google.android.packageinstaller, PID: 20328
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2271)
	at android.os.Parcel.writeParcelable(Parcel.java:2584)
	at com.android.packageinstaller.PackageUtil$AppSnippet.writeToParcel(PackageUtil.java:151)
	at android.os.Parcel.writeParcelable(Parcel.java:2584)
	at android.os.Parcel.writeValue(Parcel.java:2485)
	at android.os.Parcel.writeValue(Parcel.java:2362)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1367)
	at android.content.Intent.writeToParcel(Intent.java:11807)
	at android.os.Parcel.writeTypedObject(Parcel.java:2203)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2077)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1873)
	at android.app.Activity.startActivityForResult(Activity.java:5615)
	at android.app.Activity.startActivityForResult(Activity.java:5573)
	at android.app.Activity.startActivity(Activity.java:6071)
	at android.app.Activity.startActivity(Activity.java:6038)
	at com.android.packageinstaller.PackageInstallerActivity.startInstall(PackageInstallerActivity.java:701)
	at com.android.packageinstaller.PackageInstallerActivity.lambda$bindUi$0(PackageInstallerActivity.java:479)
	at com.android.packageinstaller.PackageInstallerActivity.$r8$lambda$RCIm8wl1VPqdfQgkgmrBIDbuvOQ(PackageInstallerActivity.java:0)
	at com.android.packageinstaller.PackageInstallerActivity$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.android.packageinstaller.AlertController$ButtonHandler.handleMessage(AlertController.java:144)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by crackededed** [comment]
try this apk: [app-release.zip](https://github.com/crackededed/Xtra/files/13215065/app-release.zip)

**Comment by squee666** [comment]
`--------- beginning of crash
11-01 18:25:17.849 25876 25876 E AndroidRuntime: FATAL EXCEPTION: main
11-01 18:25:17.849 25876 25876 E AndroidRuntime: Process: com.google.android.packageinstaller, PID: 25876
11-01 18:25:17.849 25876 25876 E AndroidRuntime: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2271)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Parcel.writeParcelable(Parcel.java:2584)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at com.android.packageinstaller.PackageUtil$AppSnippet.writeToParcel(PackageUtil.java:151)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Parcel.writeParcelable(Parcel.java:2584)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:2485)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:2362)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1389)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1367)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.content.Intent.writeToParcel(Intent.java:11807)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Parcel.writeTypedObject(Parcel.java:2203)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2077)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1873)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5615)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5573)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:6071)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:6038)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.startInstall(PackageInstallerActivity.java:701)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.lambda$bindUi$0(PackageInstallerActivity.java:479)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.$r8$lambda$RCIm8wl1VPqdfQgkgmrBIDbuvOQ(PackageInstallerActivity.java:0)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at com.android.packageinstaller.AlertController$ButtonHandler.handleMessage(AlertController.java:144)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8194)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-01 18:25:17.849 25876 25876 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: FATAL EXCEPTION: main
11-01 18:25:22.603 25937 25937 E AndroidRuntime: Process: com.google.android.packageinstaller, PID: 25937
11-01 18:25:22.603 25937 25937 E AndroidRuntime: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2271)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Parcel.writeParcelable(Parcel.java:2584)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at com.android.packageinstaller.PackageUtil$AppSnippet.writeToParcel(PackageUtil.java:151)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Parcel.writeParcelable(Parcel.java:2584)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:2485)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:2362)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1389)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1367)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.content.Intent.writeToParcel(Intent.java:11807)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Parcel.writeTypedObject(Parcel.java:2203)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2077)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1873)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5615)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5573)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:6071)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:6038)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.startInstall(PackageInstallerActivity.java:701)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.lambda$bindUi$0(PackageInstallerActivity.java:479)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.$r8$lambda$RCIm8wl1VPqdfQgkgmrBIDbuvOQ(PackageInstallerActivity.java:0)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at com.android.packageinstaller.AlertController$ButtonHandler.handleMessage(AlertController.java:144)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8194)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-01 18:25:22.603 25937 25937 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`

**Comment by thinkpad4** [comment]
I don't have Android 14 yet but it's coming to my S23 soon.  I'm wondering if it's cause the app is made for Android 5 and up, in 14 they said they are going to block side loaded apps below Android 6.

**Comment by squee666** [comment]
> I don't have Android 14 yet but it's coming to my S23 soon. I'm wondering if it's cause the app is made for Android 5 and up, in 14 they said they are going to block side loaded apps below Android 6.
well it lets me sideload it fine just package installer has issues

**Comment by thinkpad4** [comment]
Any word on a fix for installing this on Android 14?  My s23 is gonna get it very soon.

**Comment by crackededed** [comment]
i don't know how to fix this but i'm guessing it will work on other devices

**Comment by squee666** [comment]
• Fixed an issue that caused the package manager to crash when installing some apps.

Android 14 qpr2 beta 1 update fixed this issue
