### ISSUE TITLE
Feature Request: Videos Tab

### ISSUE THREAD

**Issue by bnhershy** [crackededed/Xtra#39]
The previous versions of Xtra had a drop-down menu to select live channels you follow, or videos from channels you follow.
Can this be implemented, either as it's own tab, or said original drop-down menu.

Cheers mate for the upkeep on this project.

**Comment by crackededed** [comment]
yes i will add it soon

**Comment by bnhershy** [comment]
> yes i will add it soon

Nice; cheers m8

**Comment by crackededed** [comment]
added now. you will need to relogin
