### ISSUE TITLE
[Bug] Black screen and "Player error. Retrying."

### ISSUE THREAD

**Issue by Newcool1230** [crackededed/Xtra#394]
Whenever I open a stream, the player will be black and after a few loads it gives the error. The chat functions correctly. If I turn custom proxy off it will load the stream correctly.

Version: 2.26.2
Hide ad segments: ON
Use custom proxy: ON
Custom proxy url: https://lb-as.cdn-perfprod.com/live/$channel?allow_source=true&allow_audio_only=true&fast_bread=true
HTTP proxy settings: 
- Host: firefox.api.cdn-perfprod.com
- Port: 2023

**Comment by crackededed** [comment]
turn off Hide ad segments. it doesn't work correctly so it usually causes errors if there's ads

**Comment by crackededed** [comment]
i tried this custom proxy and it was giving a 404 error which then redirected to ttv lol pro github page. the player should try to open the stream without proxy on 404 errors but i think it was trying to open the github link and that was causing the error. the proxy is working now but there's preroll ads. if you're getting ads or that error, you should turn off Use custom proxy and turn on Proxy multivariant playlist in HTTP proxy settings. you can also try turning on Proxy playback access token and then it should do pretty much the same thing as a custom proxy with the http proxy instead.

**Comment by crackededed** [comment]
just tested it again. got 1 preroll and probably like 10 playlists without ads. seems to work now. you can keep using it if it works for you

**Comment by crackededed** [comment]
it's working for me right now. if you get the error a log from adb would be nice

**Comment by Rita-Magrita** [comment]
I have this issue when watching vods. I don't have any proxy or other internet progs on my tablet, just wi-fi, chrome and xtra working in moment. It happens pretty often, and pretty long, and any restarts or clearing program cache don't fix it. It fixes itself by a few hours. Also, I'm sorry for my English, I know it's bad, hope I write this all normal.
