### ISSUE TITLE
[Bug] Correctly handle the Default player quality

### ISSUE THREAD

**Issue by Oleepre** [crackededed/Xtra#399]
The Default player quality setting's behavior is not consistent and presents a few problems, specially when handling VODs and Clips.

 1_ If the default quality is set to 160p or the Saved Value at that time is 160p, then Clips will play at Max resolution which usually is 1080p. 
 Expected behavior: play the clips at 360p since it's the lowest quality available instead of the highest.

 2_ If the VOD or Clip have a resolution named after a specific framerate, then the Default/saved player quality will fail to work.
 Example: with a default/saved value of 480p, the setting will be ignored if the available resolutions are labeled as 480p30/480p50/480p60 and instead will default to AUTO. Same happens with 360p, 720p, if the resolution mentions a framerate.
 Expected behavior: respect the default/saved resolution value regardless of the framerate of the VOD/Clip.

**Comment by crackededed** [comment]
i think this should work correctly now

**Comment by Oleepre** [comment]
Testing on the last version.
 When setting the Default Player Quality to a fixed value, the setting works correctly now across VODs, Clips and live streams. (360p->360p30, 160p->360p in clips, etc).
 But when it's set to "Saved Value" it stops working as intended and behaves the same way it did before these changes. Selecting 160p on a stream and then going to a clip will go back to 1080p, AUTO with different framerates, etc.

**Comment by crackededed** [comment]
saved quality works the same way now
