### ISSUE TITLE
Am I the only one that keep getting a Pop up window of  the official twitch website inside the app?

### ISSUE THREAD

**Issue by Hammoudi2299** [crackededed/Xtra#401]

**Comment by Hammoudi2299** [comment]
![Screenshot_2023-12-25-04-39-00-887_com.github.andreyasadchy.xtra.jpg](https://github.com/crackededed/Xtra/assets/89963808/10e7f359-a9a4-44df-9f23-719e8bf66328)

**Comment by crackededed** [comment]
turn off Use integrity token in settings

**Comment by Hammoudi2299** [comment]
> turn off Use integrity token in settings

Thank you.
