### ISSUE TITLE
Is it possible to have the new Material 3 not be purple?

### ISSUE THREAD

**Issue by thinkpad4** [crackededed/Xtra#404]
@crackededed The blue switches of the old version looked much better, the purple reminds me of the awful purple that Twitch used/uses on their website.  Even the dark theme skews purple.  Thank you very much

**Comment by Bond198** [comment]
Or a switch to change back to the old ui.

**Comment by thinkpad4** [comment]
> Or a switch to change back to the old ui.

This would be acceptable too

**Comment by DarrenWarrenV** [comment]
> Or a switch to change back to the old ui.

This! Please, old UI was so good. I had to downgrade

**Comment by thinkpad4** [comment]
Yeah, nobody likes Material 3 can you please switch back to Material 2 or whatever you were using before?  Change for the sake of change is pointless

**Comment by Bond198** [comment]
The sheer amount of wasted pixels is just insane.

New UI:
![Screenshot_20240106-235539](https://github.com/crackededed/Xtra/assets/5798059/20ed907b-8b1f-4177-82e2-07df2e21aaf3)

Old UI:
![Screenshot_2024-01-06-23-53-26](https://github.com/crackededed/Xtra/assets/5798059/d714208d-ca38-4de0-ae21-0d285f67935c)

**Comment by crackededed** [comment]
i think the old AppCompat theme just crashes because i updated some components to material but i'll take a look at it again

**Comment by thinkpad4** [comment]
@crackededed can you provide a link to Version 2.26.6 APK so I can do some testing myself.  I don't have a copy anymore.  Thank you very much

**Comment by crackededed** [comment]
> @crackededed can you provide a link to Version 2.26.6 APK so I can do some testing myself. I don't have a copy anymore. Thank you very much

https://github.com/crackededed/Xtra/actions/runs/7308893600/artifacts/1132617475

**Comment by thinkpad4** [comment]
Thank you

**Comment by crackededed** [comment]
there's now a setting to turn off material 3
