### ISSUE TITLE
New black theme

### ISSUE THREAD

**Issue by DarrenWarrenV** [crackededed/Xtra#410]
I updated just today. Why is black **not black** anymore and just some mixture with gray? How do you change button colors to the old white color? Why change something that was simply perfect? Can we get the option to go back to the old look please? For the time being I had to downgrade and re-follow offline over 50 streamers...

**Comment by crackededed** [comment]
> Why is black **not black** anymore and just some mixture with gray?

it's using default dark colors currently. i tried overriding the surface colors with full black but they still showed 
up as grey somehow. i'm not sure how to fix that yet

> For the time being I had to downgrade and re-follow offline over 50 streamers...

you don't need to reinstall. old versions can be installed as updates unless you're using the f-droid version

**Comment by DarrenWarrenV** [comment]
Oh man, you're right! I wasted so much time re-following and setting everything up again (using Github builds). Thank you.
The old look with the black theme is perfect, I just had to revert. I love Xtra, probably wouldn't watch Twitch as much if it wouldn't be for this app and Shelter (clone Xtra for dual streams with independent volume control).
