### ISSUE TITLE
Rewind/fast forward buttons have broken labels since 2.27.0

### ISSUE THREAD

**Issue by adem4ik** [crackededed/Xtra#411]
Version: 2.27.1
Android: 12

It looks like number labels have to small space now.

![изображение](https://github.com/crackededed/Xtra/assets/4707112/fd3d2ce9-b6bd-4760-9c28-70d8d4f95721)

**Comment by crackededed** [comment]
is this fixed now?

**Comment by adem4ik** [comment]
@crackededed yes, thank you!
![изображение](https://github.com/crackededed/Xtra/assets/4707112/64cfbd41-2f69-4ce0-9835-8e818376334e)
