### ISSUE TITLE
Firestick 4k Gen2

### ISSUE THREAD

**Issue by bigjeff22** [crackededed/Xtra#418]
Hello,

i absolutely love your apk i use it almost everyday on my tablet i tryed to install it on my firestick 4k gen 2
everything is working for the games, popular, following bar and the settings but i cannot go up/down and access the streams icons in the middle

would be fantastic if that could be fixed in the upcoming update.

thank you

**Comment by AitoZ** [comment]
On your Fire TV Stick use [S0undTV - GitHub (Standalone)](https://github.com/S0und/S0undTV/releases/latest) | [S0undTV - Google Play](https://play.google.com/store/apps/details?id=com.s0und.s0undtv) or [SmartTV Client for Twitch - GitHub (Standalone)](https://github.com/fgl27/SmartTwitchTV/releases/latest) | [SmartTV Client for Twitch - Google Play](https://play.google.com/store/apps/details?id=com.fgl27.twitch) instead, just my two cents.

**Comment by bigjeff22** [comment]
@AitoZ appreciate you took the time to write that i will check them out, thanks.

**Comment by crackededed** [comment]
#179
