### ISSUE TITLE
Cannot install on Android 14 January 2024 Security update Pixel 8

### ISSUE THREAD

**Issue by corndog2000** [crackededed/Xtra#422]
When I try to install the latest APK from f-droid I am unable to complete the installation. The little app install popup appears. But, after pressing install, nothing happens. I never get the “App Installed” notification. If I try to install the APK again right after, then I get Package Installer has stopped working error popups.

Let me know if there is anything I can do to help diagnose the problem.

**Comment by wi6ii** [comment]
Same issue for me on pixel 6

**Comment by wi6ii** [comment]
It just installed using uptodown apk installer. Only Pixel's default apk installer is not installing it

**Comment by crackededed** [comment]
https://github.com/crackededed/Xtra/issues/384#issuecomment-1813332993
update os or install some other way

**Comment by crackededed** [comment]
oh seems like there might be a way to fix it. try installing this version: [app-debug.zip](https://github.com/crackededed/Xtra/files/14048590/app-debug.zip)

**Comment by corndog2000** [comment]
> oh seems like there might be a way to fix it. try installing this version: [app-debug.zip](https://github.com/crackededed/Xtra/files/14048590/app-debug.zip)
> 

This apk worked!

**Comment by crackededed** [comment]
fixed
