### ISSUE TITLE
[Feature Request] Volume and brightness gestures support

### ISSUE THREAD

**Issue by maaaaaaaaaaaaaaaaaaaaaaaa** [crackededed/Xtra#427]
Add a right and left gestures for full-screen mode with and without chat for controlling volume and brightness. In addition, an option to remember and switch to the last used brightness and a second option to remember and switch to the last used volume.

**Comment by Aeon1704** [comment]
Yes! Please!
Ok, we have volume scroll, but i think we don't have anything to deal with brightness. My huawei devices makes video-player way too bright with no ability to lower it. Whatever it is HDR or something else, but... i don't have any setting to disable it. Please add Brightness control, swipe or gesture, to control video-player brightness ( not system brightness ),

Xtra makes it unbearable to watch Twitch in night time for me :(
Lowering system-wide brightness will dull everything else. Youtube app has same problem, but i found GrayJay which has Brightness gesture support inside the app.

**Comment by crackededed** [comment]
#362
