### ISSUE TITLE
Record Button

### ISSUE THREAD

**Issue by nwyr** [crackededed/Xtra#432]
Is it possible to add a button to record the currently viewed live stream like vlc on pc? The button is on the player button or menu. When pressed it shows bubbles.

The file recorded as a single ts file based on the viewed player quality may be stored in the downloads tab or in a new tab.

![Screenshot_2024-02-19-15-02-02-597_com miui home](https://github.com/crackededed/Xtra/assets/25812455/dedf7a7c-4120-476a-bce4-97693d9d928d)

![Screenshot_2024-02-19-15-02-40-332_com miui home](https://github.com/crackededed/Xtra/assets/25812455/c040c66d-49c3-40c1-84e1-549f3465d6de)

I know that I can screen record, but when I screen record, I can't do anything else and the recorded file size will be large according to the resolution of the screen.

**Comment by crackededed** [comment]
#363
