### ISSUE TITLE
cant login because i cant scroll/accept cookies

### ISSUE THREAD

**Issue by BeatZeps** [crackededed/Xtra#433]
Hello I have a problem my session has expired i tried to login again but now i have to accept the cookies again but I can't scroll down to accept them. The newest version is installed

![Screenshot_20240219-184745_Xtra](https://github.com/crackededed/Xtra/assets/20957162/5c0d3630-2bc3-4624-8c9a-cb3fe4951953)

I already accepted them on the site and the official app but it doesn't go away.

**Comment by crackededed** [comment]
try in landscape mode

**Comment by BeatZeps** [comment]
Sadly no same problem cant reach the accept button. I also tried zooming out but i can only zoom in. Cant see or press the accept button at all

![Screenshot_20240223-182425_Xtra](https://github.com/crackededed/Xtra/assets/20957162/ac4de5cd-e268-4136-b69a-56f302387425)

**Comment by BeatZeps** [comment]
That workaraound worked thank you very much

**Comment by marc1uk** [comment]
I have a simliar issue in that the embedded webview has no URL bar, so when the app asks me to "copy the URL" .... i can't?
