### ISSUE TITLE
[Suggestion]: View deleted VODs

### ISSUE THREAD

**Issue by VladBladick** [crackededed/Xtra#435]
I’m not sure if this is possible, since I haven’t seen such a function implemented anywhere in applications. But there is a browser extension Twitch VOD Downloader, using it, you can immediately view remote VOD online. Many streamers delete or cut off the broadcast, I would like to watch it in full. On Android so far only using kiwi browser you have to look, I haven’t seen a more convenient way yet. Maybe you can tell me something, thanks in advance.

**Comment by crackededed** [comment]
deleted vods might work if you have them bookmarked in xtra

**Comment by crackededed** [comment]
yeah you would need to bookmark the vod while it is still available

**Comment by VladBladick** [comment]
Thanks for the help and explanation
