### ISSUE TITLE
Occasionally cannot download VODs of lower qualities

### ISSUE THREAD

**Issue by QmZh** [crackededed/Xtra#438]
Sometimes for some streams, when I click to download lower quality VODs, the app will exit. Mostly I cannot download any VOD other than the highest quality one, sometimes it's just some qualities and there isn't a subscriber only toast. I have checked using https://github.com/lay295/TwitchDownloader that lower quality VODs is actually downloadable. The appearance of the issue is a little rare, 1 in 50 or so. Also my downloading is often near the expire time so providing an example is a little hard. I will try to provide a video id the next time I encounter this issue.

**Comment by QmZh** [comment]
Find one but the time is very limited now. It's 2012024074

**Comment by QmZh** [comment]
> Find one but the time is very limited now. It's 2012024074

The original quality is 936p60, the streamer is EvilToaster. I am also downloading the 160p VOD using TwitchDownloader CLI.

**Comment by crackededed** [comment]
> Find one but the time is very limited now. It's 2012024074

it's already expired?

**Comment by QmZh** [comment]
> > Find one but the time is very limited now. It's 2012024074
> 
> it's already expired?

Yes but I tried other VODs of the same streamer and there is the same issue with VOD that has 720p as quality option. For example on February 13th, for VOD id 2061705038, 936p60 and 720p60 are fine but 720p and downwards cannot be downloaded, audio only is fine, VOD direct watching are all fine

> are you trying to download sub only vods? if you're not logged in the qualities are just guesses. some of them might not actually exist. i think there's a way to fix this and get the correct qualities though

I try watching all the qualities by directly click, watching is fine

**Comment by QmZh** [comment]
Also on February 1st the first VOD and on December 24th 2023. TwitchDownloader works fine too.

**Comment by crackededed** [comment]
on 2061705038 the source quality has 4823 segments but 360p only has 4812. how is that possible? it's crashing because xtra is trying to download segments that don't exist.

**Comment by crackededed** [comment]
fixed
