### ISSUE TITLE
Rarely it downloads a wrong VOD

### ISSUE THREAD

**Issue by QmZh** [crackededed/Xtra#439]
I have been using Xtra on two phones and encountered this issue 1 in 200 times or so. Sometimes I try to download a VOD and it downloads another one of another streamer of the same day, with attempt to download same length of video, and also when I try to download it again it often just downloads yet another random VOD of another streamer that I followed in Xtra. Also I checked with https://github.com/lay295/TwitchDownloader that the desired VOD is downloadable. I have encountered this issue on both phones. Next time I will provide a VOD id.

**Comment by QmZh** [comment]
This happens when I try to download multiple VODs, remove one in the queue and download another quality. 

Another thing is that sometimes the downloading queue is not in the order that I click download, when I click too fast

**Comment by crackededed** [comment]
the queue works differently now so this is probably fixed
