### ISSUE TITLE
Sometimes it doesn't proceed to download next VOD in queue

### ISSUE THREAD

**Issue by QmZh** [crackededed/Xtra#442]
When it happens, next VOD will stuck in PENDING, one of the before VODs will show DOWNLOADING 100%.

If I delete the 100% one or restart the app, it still stucks. Also the "100%" one is not fully deleted, the m3u8 file will remain.

If I restart the phone, it proceeds to download the remaining VODs, but the "100%" doesn't go away. 

Another thing is that the notification of the app will show many finished downloads( no DOWNLOADING 100% in app, just same as normal one) as still in the downloading phase, with download bar apparently full. This notification thing started to happen in recent versions.

**Comment by QmZh** [comment]
I'm using version 2.30.6 from F-droid. After deletion in the Downloads tab while it's downloading, it still tries to download the VOD, causing it to stuck when the VOD is unavailable. This state will end when the phone restarts or when the app exits when I try to download an unavailable VOD.

**Comment by crackededed** [comment]
this should be fixed now
