### ISSUE TITLE
App Randomly Closes

### ISSUE THREAD

**Issue by Fairweather-Furry** [crackededed/Xtra#446]
After the latest release, Xtra closes itself while watching streams. Picture-in-picture seems to prevent it, but attempting to return to the app will close the app. F-Droid 2.29.1, Pixel 7a, stock OS.

**Comment by Ikeruga** [comment]
Same. Was trying to find logs to share but I don't see anything. I'm on F-Droid 2.29.1, fairphone 3, e-os.

**Comment by crackededed** [comment]
https://github.com/crackededed/Xtra/issues/445#issuecomment-1978770158
