### ISSUE TITLE
Mentioning users does not work correctly(see scr.-s) from v. 2.27.4 and above

### ISSUE THREAD

**Issue by oxota74** [crackededed/Xtra#458]
![Screenshot_2024_03_25_00_45_54_812_com_github_andreyasadchy_xtraa](https://github.com/crackededed/Xtra/assets/87602646/5ddf0ab6-65be-4279-ac9a-4165c5ef4815)
Successful connection to the streamer, the first 2 messages after connection

![Screenshot_2024_03_25_00_45_57_289_com_github_andreyasadchy_xtraa](https://github.com/crackededed/Xtra/assets/87602646/24939b9c-88c6-4dd1-8478-5614e89ac5bb)
The first input @

![Screenshot_2024_03_25_00_46_06_029_com_github_andreyasadchy_xtraa](https://github.com/crackededed/Xtra/assets/87602646/b0283c1c-cfa3-4b27-8505-075713672f30)
a message from a third user

![Screenshot_2024_03_25_00_46_12_827_com_github_andreyasadchy_xtraa](https://github.com/crackededed/Xtra/assets/87602646/685f17eb-c406-4c23-b070-cbcebca878a5)
the second input @

**Comment by crackededed** [comment]
fixed
