### ISSUE TITLE
Logging Out

### ISSUE THREAD

**Issue by nightznero** [crackededed/Xtra#459]
Helloz,

I have a question/issue.
From time to time my acc is logging out.
I m logged on Xtra and on Modded version of Twitch but issue is only present on Xtra. Wondering why,everytime i log in into Xtra i have to accept permission to allow Twitch Tv to authorize Xtra,well...Its because auth expired or?

**Comment by nightznero** [comment]
> tv authorization is used to get a second token that can do things a normal token can't like following channels and collecting channel points. the normal token expires after some days of inactivity. tv token shouldn't expire. you can change this setting and then login if you want to use a token that never expires: Settings -> Api settings -> Tokens -> Get token for selected apis -> GQL

just to clarify. I m speaking about phone device,not tv. If i choose only GQL Token does that mean that points will not be auto collected ?

**Comment by crackededed** [comment]
> If i choose only GQL Token does that mean that points will not be auto collected ?

no. you need the gql token for that

**Comment by nightznero** [comment]
> > If i choose only GQL Token does that mean that points will not be auto collected ?
> 
> no. you need the gql token for that

well helloz again.
Token has been changed when i got info from you right away but... today once again i have been logged out :X
