### ISSUE TITLE
Bug in following tab

### ISSUE THREAD

**Issue by jojobozo** [crackededed/Xtra#46]
Is it normal that I don't see my offline followed channels in live?

**Comment by crackededed** [comment]
no. it's fixed now

**Comment by xfzv** [comment]
I'm having the same issue lately with 2.0.4, installed from F-Droid. The live tab always says "Nothing here" despite some of my offline followed channels being live.

**Comment by crackededed** [comment]
2.0.4 on fdroid is the android 4 version and local follows don't work on that version.

**Comment by xfzv** [comment]
> 2.0.4 on fdroid is the android 4 version and local follows don't work on that version.

Thanks for the info. I've just updated to 2.0.5, all good now. :ok_hand:
