### ISSUE TITLE
Feature Request: Add VODs bookmarks

### ISSUE THREAD

**Issue by LukasThyWalls** [crackededed/Xtra#48]
Hello.

The idea is change the "Downloads" section to a "Saved" section (or something like that) and add two tabs inside, one as "Downloads" and working as is working right now, and other as "Bookmarks" to list bookmarked VODs (they can be sorted if it's possible).

Then add a option in every video to add/delete to bookmarks.

Issues upfront:
* A live stream could be bookmarked, but instead bookmarking the live stream, bookmark the corresponding VOD is generating.
* VODs dissapears, so in the list they can auto-dissapear too, or mark them as deleted/gone. Bonus idea if there is a way in the API to know when every VOD is going to dissapear and show that information.

Thanks!

**Comment by crackededed** [comment]
that seems possible. wouldn't it be better to have both bookmarked and downloaded vods in the same tab so all of them could be sorted/searched through at once? api doesn't tell when vods are going to get auto deleted. it is possible to check if the user is affiliate/partner but some people have vods that get saved for like 1 year or more.

**Comment by LukasThyWalls** [comment]
I don't know, i mean, i think that should be decision of you and whoever at the end do the job.

Depending of what you want: Actually you have a "Games", "Popular", "Following" and "Downloads" (below, i call them "Sections"), and in the lastest versions you put inside "Following" section the tabs (above) "Games", "Live", "Videos" and "Channels". The other sections don't have any tabs.

So, if you want the content more distributed by what content is, you can have as sections "Popular", "Following" and "Saved"
- "Popular" section with two tabs ("Games" and "Channels", both with the old "Games" and "Popular" content respectively),
- "Following" section with the actual tabs ("Games", "Live", "Videos" and "Channels", as all )
- "Saved" section with two tabs (The "Bookmarks" talked in this thread, and "Downloads", with the content of the "Downloads" section.

But, if you want more direct access to all content, you can have a lot of sections as "Games", "Popular", "Following", "Saved" and "Downloads", and only with tabs in the "Following" section ("Games", "Live", "Videos" and "Channels").

In my opinion, the first option i described seems good, maybe creating a section for "Live" extracting the tab from "Following" as is the most useful and the default (for me) to show. And that make rooms for other tabs (and sections) i there is ideas to make ones.

But like i said, the one who makes it is the one to choose how to do it, and also we are moving away from the original topic...

**Comment by hurrdurr1** [comment]
I would love this feature so much. I use screenshots to remind myself of VODs I want to watch later, but being able to bookmark VODs would be SO much better.  

> api doesn't tell when vods are going to get auto deleted. it is possible to check if the user is affiliate/partner but some people have vods that get saved for like 1 year or more.

If it's possible to check partner and/or Amazon prime status, it should be as simple as "if either or both, then autodeletion 60 days from VOD date, otherwise 14 days"? For channels who's VODs don't get autodeleted, if it can't be checked automatically, maybe make a whitelist or something that people can fill with channels that don't autodelete? Those channels seem very rare, so it wouldn't be much trouble I think.

-----

Another suggestion: Add an option per bookmarked VOD to send a notification one or more days before they get deleted, as some VODs may be more important than others.

**Comment by LukasThyWalls** [comment]
Other way to do it is similar of how official Twitch App does, but better, and maybe is more easy to implement now.

What it does is to list the last five videos that you seen in the past, the ones that it have info of where you left it. The main problem with it is the official Twitch App doesn't allow to delete an item of that list, you can only see more and the list is overwrited (it can only list five) or the video is deleted.

Because Xtra is now remembering the time of the VODs you saw, the point is to list all videos with that information. However, it would need a option to "clear" that information and forget that video. That would work in the same way that bookmarking.
Also it can be an option to bookmark the video but in the beginning, and it can be to add that time seek information to "00:00:00" or "00:00:01" or something like that.
And something to add to this, and the official Twitch App does, is for a Live you saw, remember the time you left in its respective VOD. This could be a request not only for this, it could be useful in a whole for the App.

About the VODs deletion, i'm afraid that maybe is a bit difficult to calculate when it could be deleted by Twitch, knowing also that the streamer itself can delete it too, and there are video that will not be autodeleted (highlights and things like that). So to simplify can be done deleting the missing videos, or showing a blank item saying "This VODs is missing". That can be done if the app have time seek info for a video that is not there, and you can "forget" clearing that information (which is the same as remove from the list).

**Comment by LukasThyWalls** [comment]
I was testing a bit since a few days ago you added this functionality to Xtra, i saw some things:

* The auto deletion feature seems good, although i don't know if is needed that accuracy... only to know that a VOD is going to be 59 days maybe is enough.
* I detected that if you add to bookmarks a VOD from a still Live streaming, it appears in the list with the time in that moment (For example, i added one at 16m:44s, the live streaming reach more than 9h... in the list it still shows 16:44), although when you tap to see it, it plays entirely. If i'm not mistaken, you are creating a item with all the info at the moment of adding the bookmark, similar of how a download item is (but, in this case without downloading the video). Also it lacks the thumbnail although the finished VOD have one. Like i said above, having some way to add an Live stream to bookmarks and adding the respective VOD (first partially, later when is full) to it, is how it could be work.
* The VODs added to bookmark can be added again to bookmarks if you look for them, but what is doing is adding it to the list, and removing it, although you always see "Add bookmark" as option.
* Having Downloads and Bookmarks listed in the same section is a bit overpopulated.

**Comment by hurrdurr1** [comment]
> The auto deletion feature seems good, although i don't know if is needed that accuracy... only to know that a VOD is going to be 59 days maybe is enough.

As someone who tends to procrastinate until the last moment with a lot of things, I appreciate the precision a lot. There have been many times where VODs got deleted before I could watch or DL them because you couldn't tell what time streams had started, and thus what time they'd get deleted. The seconds aren't super useful and could potentially be cut out for the sake of a slightly cleaner interface, but minutes are still useful for me

Thanks for adding this feature dev <3

**Comment by LukasThyWalls** [comment]
> > The auto deletion feature seems good, although i don't know if is needed that accuracy... only to know that a VOD is going to be 59 days maybe is enough.
> 
> As someone who tends to procrastinate until the last moment with a lot of things, I appreciate the precision a lot. There have been many times where VODs got deleted before I could watch or DL them because you couldn't tell what time streams had started, and thus what time they'd get deleted. The seconds aren't super useful and could potentially be cut out for the sake of a slightly cleaner interface, but minutes are still useful for me
> 
> Thanks for adding this feature dev <3

Fair enough 👍

**Comment by crackededed** [comment]
i made a new list for bookmarks because some stuff wasn't really working well with downloads and bookmarks on the same list. old bookmarks need to be re-added manually after updating

**Comment by LukasThyWalls** [comment]
> i made a new list for bookmarks because some stuff wasn't really working well with downloads and bookmarks on the same list. old bookmarks need to be re-added manually after updating

I just tested and it seems that the bookmarks list order are from higher to lower autodelete time, if i'm not mistaken? In the last version was by order of adding in the list.

About the autodelete time, i tested about a Affiliate streamer that marks as the time autodelete about 15 days, but they are videos from more to that. In fact those videos bookmarks doesn't show autodelete time, and i have other one with 20h left for that channel and i want to know what happens when it reach the time. Also i have a video from other channel, that the last video is from 2 months and it should dissapears by tomorrow (is the oldest one in its channel). Highlight doesn't show the autodelete time because they aren't going to be deleted.

Also i want to ask about the "Ignore auto deletion for this user" option. What exactly does?

**Comment by crackededed** [comment]
having prime also gives 60 days of vods even when not partner. nothing happens when the time is reached. you have to delete them manually. ignore option just allows you to hide the timer for that user. useful when you know the timer is wrong.

**Comment by LukasThyWalls** [comment]
> having prime also gives 60 days of vods even when not partner. nothing happens when the time is reached. you have to delete them manually. ignore option just allows you to hide the timer for that user. useful when you know the timer is wrong.

Ah, that's why. Understood. Maybe instead of putting "Auto-deleted in XXd XXh XXm XXs", should be "Estimated auto-deletion in XXd XXh XXm XXs". Also the seconds maybe is too much to have there.
Related, and if one day it can have some kind of notifications about nearly auto-deletion, also the app can give an option to download as last option.

Other things i tested with the last build:
* Now the add/remove bookmarks shows in the VODs as it should when they are in the list or not.
* Deleted VODs are listed as normal videos, without anything that says that the VOD is gone, however if you tap on them, it tries to play a 00:00 video, and obviously doesn't work.
* VODs added from a Live streaming when is still live, i detected what it does is in a briefly milisecond when is loading the list (and before it shows the auto-deletion time), it shows the original time when i added it and no thumbnail (if the Live is still going when i added), and after that it updates the time and thumbnail, but not the name of the Bookmark if it was changed afterwards in the VOD.

If i'm not mistaken, these two last things looks like that when in the bookmarks database and item is added, it's added with the info that it has in that moment, and after when loads the list the info is updated every first load of the list, but it's not updated in the database itself. Doing that it can change all the information once and it only checks if everything is the same, and you will not see the list changing and flickering the thumbnail every time it loads, and also it can add a text over the VODs detected as deleted and then they will be different to those that the auto-deletion are reached. 
Thinking now about that: If a 15 days auto-deletion time comes but the VOD is still there, maybe it can infer that it's really a 60 days of auto-deletion if there isn't other thing that change that status (except deletion by the streamer).
