### ISSUE TITLE
Request: check file completeness while downloading

### ISSUE THREAD

**Issue by QmZh** [crackededed/Xtra#481]
Some of the ts files are incomplete, some are even empty when I encounter a network problem and the app won't check file completeness. Currently, I use ffmpeg to check that the ts files are no shorter than 10, 12, or 12.5 seconds and redownload them in the app. Could you add this function in your app?

**Comment by QmZh** [comment]
> turn on Use WorkManager for downloads in settings and see if it still happens

Actually it's happening when this option is on. I had this option on and found that it can download multiple VODs at the same time and when I redownload a VOD (since some files are incomplete and I move them to another folder), already downloaded files won't be downloaded again, which is desirable. If I don't use the WorkManager, the download is only sequential (and slower) and will stuck when a VOD download stuck.

**Comment by crackededed** [comment]
this shouldn't be a problem anymore because incomplete segments are redownloaded now
