### ISSUE TITLE
App forgets current position in VOD randomly

### ISSUE THREAD

**Issue by maritz** [crackededed/Xtra#488]
When watching VODs Xtra seems to randomly forget the scroll position where you left the app in - be it by locking the screen or closing it. In that case going back into the app, the vod starts from 0 (as in, I open Xtra, it starts in the VOD already, but just at timestamp 0).

I can't figure out a pattern to it, because usually it remembers the position. It appears however that it got way worse the last couple of days.

~It would also be cool if the headphone "scroll forward/backward" buttons would do the 10s forward/backward instead of "go to start of vod".~ (covered by #334)

**Comment by tuxayo** [comment]
> It would also be cool if the headphone "scroll forward/backward" buttons would do the 10s forward/backward instead of "go to start of vod".

I think it's related to https://github.com/crackededed/Xtra/issues/334

**Comment by tuxayo** [comment]
I have the same issue repeatedly, it's a remainder of https://github.com/crackededed/Xtra/issues/350

**Comment by tuxayo** [comment]
My only reliable way to not lose position is to swipe away xtra from the recent apps.

Other wise I will often lose position to 0 or the previous position where I closed the app from recent apps.

**Comment by crackededed** [comment]
#350
