### ISSUE TITLE
advertisement appears

### ISSUE THREAD

**Issue by Gergedanyarra** [crackededed/Xtra#492]
While watching the broadcaster, an advertisement suddenly appeared on the screen.  I was wondering if my publisher had given it to me, so I opened it again and tried it.  No, the ad was seriously coming out.  It's happened in 1 publisher so far.  and I'm sure it wasn't given by the publisher.  + the application is very nice.  thank you for your efforts

**Comment by crackededed** [comment]
you can try setting up a proxy in settings

**Comment by throwaway26425** [comment]
> you can try setting up a proxy in settings

wait, how do we do that?

I have no knolewdge about that.
