### ISSUE TITLE
Crashing when trying to watch downloaded VOD

### ISSUE THREAD

**Issue by FJIauKa** [crackededed/Xtra#494]
POCO F2 Pro
Android 12

**Comment by FJIauKa** [comment]
![Screenshot_2024-05-27-12-01-05-822_com miui bugreport](https://github.com/crackededed/Xtra/assets/170904760/f1f773d4-996d-4dcb-a9f3-ac06d2b34dce)
It crashes with this report

**Comment by FJIauKa** [comment]
https://github.com/crackededed/Xtra/assets/170904760/695fbbbd-f5d7-49b6-8332-13f05e38a02a

**Comment by crackededed** [comment]
change Min Buffer to be larger than Buffer for playback in Buffer settings

**Comment by FJIauKa** [comment]
worked, thanks
