### ISSUE TITLE
All or custom 7TV/BTTV/FFZ emotions are periodically missing from the list of recent

### ISSUE THREAD

**Issue by oxota74** [crackededed/Xtra#496]
![IMG_20240528_182441](https://github.com/crackededed/Xtra/assets/87602646/25a560b3-57c8-4cda-a3c8-ecbdd5c5f47a)
Only Twitch emotes

![IMG_20240528_182458](https://github.com/crackededed/Xtra/assets/87602646/057db499-07c9-4486-96ca-9b21f87d2020)
Global 7TV/BTTV/FFZ and Twitch emotes

![IMG_20240528_182520](https://github.com/crackededed/Xtra/assets/87602646/2fdc300f-2f37-48ba-89be-efa66bbb894e)
All emotes (normal state)

Sometimes this is fixed by re-logging into either streaming or the app (the second solution works better)

It is also in one of the issues #376, but is less precisely explained

**Comment by crackededed** [comment]
i think currently you need to have all of the emotes loaded before opening the emote picker. you can just wait a bit before opening it and it should work

**Comment by oxota74** [comment]
@crackededed , that's the point. I'm watching one channel with about 1000 7TV emotions, I downloaded them all, including Twitch emotions, using high-speed Internet, and the application cache increased by about 500-600 megabytes, but it still doesn't help. As if the problem is in this list "of recent...", he specifically does not want to download for some reason. I don't understand it yet, I want to find out too.

**Comment by theridon** [comment]
Loaded as in show scrolling down to see all of them in the emote lists in app? Doesn't make a difference for me.

**Comment by crackededed** [comment]
you have to wait a bit before opening the emote menu

**Comment by theridon** [comment]
Does not work unfortunately

**Comment by crackededed** [comment]
i think this is fixed now

**Comment by theridon** [comment]
Nope

**Comment by crackededed** [comment]
> Nope

what's wrong with it now?

**Comment by oxota74** [comment]
at the moment, from version 2.37.0, there is no problem
