### ISSUE TITLE
Emotes order and recent 

### ISSUE THREAD

**Issue by jippyuk** [crackededed/Xtra#5]
Would be great if you can find a way to put the emotes available for you if sub at the top of the emote list when you click it.
Also it takes up to ten seconds of blank before they start to show on selection.
And finally I use emotes but they don't show in recent?

Great work otherwise :)

**Comment by crackededed** [comment]
i think everything is fixed now

**Comment by jippyuk** [comment]
Frequent is fixed now thanks for that!
Emotes load faster from twitch now.
Still have some of the current channel emotes appearing further down the list but not sure if you can fix that?
Would be nice to have a line separating the channel ones against all the others.

Not sure if possible though. Thanks for all the work!

**Comment by crackededed** [comment]
channel emotes are at the top now
