### ISSUE TITLE
Feature request: Option to disable send a message to chat

### ISSUE THREAD

**Issue by LukasThyWalls** [crackededed/Xtra#50]
Hello.

I don't know exactly how to name it, but the point is to add an option to show the chat, but don't allow to write to the chat in a live stream, so it doesn't appear in the chat the line to write a message and the emotes, like happens in the vods.

The main reason is because i see channels in other languages, and i don't want to write something by mistake and send it if i touch the phone in a wrong way, because most of the time i'm lurking and i don't want to interact with the channel.

It could be easier and enough to add a global option in settings to do that (and go here to enable/disable it at any moment), but if it ould have a toggle by channel somehow (i didn't think how and where could it be) remembering the setting, it could be perfect.

Thanks.

**Comment by Kkeev** [comment]
It already exist, turn on chatbar toggle, then tap on an ongoing stream then tap the icon.

**Comment by LukasThyWalls** [comment]
D'oh! 
I had disabled the icon... sorry.

Closing.
