### ISSUE TITLE
[Feature Request] Use entire screen width area

### ISSUE THREAD

**Issue by emilys314** [crackededed/Xtra#501]
Currently, the player + chat will limit  the width to stop where the camera cut out area is. This can cause the player to scale down smaller if the chat is enabled.

It would be great if the chat + video player can use the full width of the device's screen. For example, the pixel line up of phones have a screen ratio of 21:9. And most twitch streams are 16:9. This enhancement could enable you to watch full screen if the chat size was 5:9.

**Mockup**

Current:
![current](https://github.com/crackededed/Xtra/assets/93456589/f47513e7-3d96-45ef-9d1f-e4499b4ebddf)

Request:
![proposed](https://github.com/crackededed/Xtra/assets/93456589/8354ab88-b0d2-43b0-a571-798dcafdf3df)

**Comment by crackededed** [comment]
Settings -> Ignore display cutouts -> Always

**Comment by emilys314** [comment]
Oh. Lol, nice
