### ISSUE TITLE
[Feature Request] Make support for Android TV

### ISSUE THREAD

**Issue by moninah850** [crackededed/Xtra#505]
No Android TV support. The application does not support control using the TV remote control.

**Comment by AitoZ** [comment]
On Android TV use [S0undTV - GitHub (Standalone)](https://github.com/S0und/S0undTV/releases/latest) | [S0undTV - Google Play](https://play.google.com/store/apps/details?id=com.s0und.s0undtv) or [SmartTV Client for Twitch - GitHub (Standalone)](https://github.com/fgl27/SmartTwitchTV/releases/latest) | [SmartTV Client for Twitch - Google Play](https://play.google.com/store/apps/details?id=com.fgl27.twitch) instead, just my two cents.

**Comment by moninah850** [comment]
> On Android TV use [S0undTV - GitHub (Standalone)](https://github.com/S0und/S0undTV/releases/latest) | [S0undTV - Google Play](https://play.google.com/store/apps/details?id=com.s0und.s0undtv) or [SmartTV Client for Twitch - GitHub (Standalone)](https://github.com/fgl27/SmartTwitchTV/releases/latest) | [SmartTV Client for Twitch - Google Play](https://play.google.com/store/apps/details?id=com.fgl27.twitch) instead, just my two cents.

I've used both.

S0undTV is a closed source code and you cannot view it without logging into your account.

SmartTV Client for Twitch does not block ads.

**Comment by AitoZ** [comment]
> > On Android TV use [S0undTV - GitHub (Standalone)](https://github.com/S0und/S0undTV/releases/latest) | [S0undTV - Google Play](https://play.google.com/store/apps/details?id=com.s0und.s0undtv) or [SmartTV Client for Twitch - GitHub (Standalone)](https://github.com/fgl27/SmartTwitchTV/releases/latest) | [SmartTV Client for Twitch - Google Play](https://play.google.com/store/apps/details?id=com.fgl27.twitch) instead, just my two cents.
> 
> I've used both.
> 
> S0undTV is a closed source code and you cannot view it without logging into your account.
> 
> SmartTV Client for Twitch does not block ads.

You are complaining about closed source but I bet you couldn't read the source code, if you can fork SmartTV Client for Twitch and add a proxy. The other solution would be #179

**Comment by moninah850** [comment]
> You are complaining about closed source but I bet you couldn't read the source code, if you can fork SmartTV Client for Twitch and add a proxy. The other solution would be #179

I already use it, but some functions still do not work, and you need to use the phone at hand. And the application itself has its own mistakes. It is inconvenient and uncomfortable.

I think to introduce support for TV navigation (D-Pad) in Xtra would be easy to solve this problem.

**Comment by crackededed** [comment]
#179
