### ISSUE TITLE
Problema no chat

### ISSUE THREAD

**Issue by JupiterSkylab** [crackededed/Xtra#508]
Não aparece mais a baixa de texto do chat, então eu não posso mais digitar nada. Só tem o que os outros digitam e o vídeo, estou impossibilitado de escrever lá

**Comment by NokkGIGN** [comment]
Baixe a versão anterior, em que o chat funciona

**Comment by Tidepodsushi** [comment]
Current version (2.32.2) & (2.32.1) will allow you to sign on see your followed channels.  Join the channels but in both versions the keyboard does not pop up  and you can not chat. I confirmed that switching to different keyboard does not fix this issue. I tried both gboard and  Anysoft keyboard. Both will not open the keyboard or to start a chat. You will see the chat. But unable to interact.  This is with the recent installed from fdroid  repo.

**Comment by crackededed** [comment]
#495
