### ISSUE TITLE
chat message box is gone

### ISSUE THREAD

**Issue by BurntCrepe** [crackededed/Xtra#511]
for the past few versions of Xtra, the box to input chat messages had been completely gone. ive reinstalled, downgraded, reset settings, etc. but nothing has worked. on the xtrafortwitch subreddit theres another user with the same problem, so i know im not alone 
![Screenshot_20240618-011007](https://github.com/crackededed/Xtra/assets/173129030/0edc5bae-d4de-4469-bb29-152cd1ab2ddc)

**Comment by gd0666** [comment]
Same here.

(Not a regular twitch user and new to Xtra. Is it possible that this is due some sort of paywall? The streamers I follow are relatively popular and I've heard that some streamers used to exclusively let users use chat that donated before.)

Using the newest version off of F-Droid
Redmi Note 8 Pro (M1906G7G)
MIUI 12.5.7
Android 11 RP1A.200720.011

**Comment by NOHEATED** [comment]
Same here too

**Comment by crackededed** [comment]
#495
