### ISSUE TITLE
Videos tab not showing on tablet 

### ISSUE THREAD

**Issue by U53R3RR0R** [crackededed/Xtra#514]
Hello. I have Xtra installed on my phone and on my tablet.

On my phone there is a videos tab in the following section.

On my tablet there is not.

I'm using the latest build on both my phone and tablet.

My phone is running Android 13. My tablet is running Android 12.

![Screenshot_2024-06-22-10-18-22-130](https://github.com/crackededed/Xtra/assets/153846300/4a8b9540-2c56-4f98-a71b-017099b30324)

**Comment by U53R3RR0R** [comment]
![Screenshot_2024-06-22-10-28-52-666_com github andreyasadchy xtra](https://github.com/crackededed/Xtra/assets/153846300/801caaa4-8e09-4e10-a5f9-97b9fccd8c8d)

**Comment by crackededed** [comment]
you need a gql token for the videos tab. check if you have it in Settings -> Api settings -> Tokens -> GQL token. you can get one by logging in to xtra without using the external browser method or using a pc web browser or just copy it from your other device

**Comment by U53R3RR0R** [comment]
This solved my problem. Thank you so much!
