### ISSUE TITLE
Download stops progressing -- bad connectivity ?

### ISSUE THREAD

**Issue by CelianGdfrd** [crackededed/Xtra#532]
I'm in a place with poor connectivity, like ADSL that breaks every 20 minutes and stuff. I'm downloading with Xtra to have replays on the go.

After some time, download stops progressing. I wonder if it is caused by the internet connection being lost and resuming, but Xtra not detecting the resuming. Stopping and starting again the download makes it work again, until it doesn't.

I'll be able to test from a stable connection in a few days.

**Comment by CelianGdfrd** [comment]
With stable connection, download still stops randomly after 3-5%. Has to be stopped and restarted to progress correctly.

**Comment by CelianGdfrd** [comment]
With last releases, I feel like downloads go faster, but they keep stopping after a time, unfortunately.

**Comment by crackededed** [comment]
#523
