### ISSUE TITLE
Emotes not loading

### ISSUE THREAD

**Issue by Andmyaxe90** [crackededed/Xtra#535]
7TV/BTTV/FFZ emotes are invisible in the chat, both live and VoDs.

**Comment by Andmyaxe90** [comment]
This is still an issue in version 2.33.5.

**Comment by Andmyaxe90** [comment]
How exactly do I do that?

**Comment by crackededed** [comment]
install an app that can view the log or use adb on pc

**Comment by Andmyaxe90** [comment]
I'm sorry, I have zero experience in programming or debugging. Can you recommend an app that I can use on Android 7?

**Comment by crackededed** [comment]
you can just search for one on google
