### ISSUE TITLE
Bug: Live chat automatic scrolling stopping randomly 

### ISSUE THREAD

**Issue by deadclicks** [crackededed/Xtra#544]
Live chat stops automatically scrolling at random intervals.

Clearing the app cache/data, and reinstalling the app, didn't fix the issue.

I believe this started happening after the latest update.

Others reporting the same issue on [reddit](https://www.reddit.com/r/XtraForTwitch/comments/1f5tfz2/chat_not_moving_after_a_few_seconds_of_viewing/)

App version: 2.34.1
Android version: 13

**Comment by crackededed** [comment]
i think this is fixed now

**Comment by deadclicks** [comment]
I tried the latest build (2.34.2) for few a hours and the issue seems to have been fixed, thank you

**Comment by beerninja** [comment]
Same problem here, but fdroid version is stuck on 2.34.0.  Looking forward to 2.34.2.  Does anyone know how long it takes for fdroid to update?
