### ISSUE TITLE
Wrong text input for certain emojis

### ISSUE THREAD

**Issue by theridon** [crackededed/Xtra#549]
The smiley faces like ;) :D etc when pressing on the emoji,  end up putting extra text that give a garbled mess in the chat and not the emojis. Anyone else experiencing this?

**Comment by crackededed** [comment]
fixed

**Comment by theridon** [comment]
Not fixed on my end, do I have to redownload the app?

**Comment by crackededed** [comment]
it should be fixed in 2.35.0
