### ISSUE TITLE
Feature Request: Show more options in every live/vod settings (Gear Icon)

### ISSUE THREAD

**Issue by LukasThyWalls** [crackededed/Xtra#55]
Hello.

To explain better this i will show you two screenshots, both of them when you tap the Settings icon (Gear),

First, Live:
![Xtra_SettingsLive](https://user-images.githubusercontent.com/1467366/161403634-e0c284a9-6ef4-44a8-9781-30818567c5ac.jpg)

Second, in VODs:
![Xtra_SettingsVOD](https://user-images.githubusercontent.com/1467366/161403646-10117afa-5c4f-4172-90ee-f6e36d48b835.jpg)

In Live streams, it only shows the quality options. In VODs, it shows quality and speed. The idea is to make both more like in VODs, and add more options to the menu, as other icons in display (Timer, aspect ratio, download, chat bar toggle..., all that can be fitted there) to keep the functionality and allowing to delete some icons in display.

Thanks in advance.

**Comment by crackededed** [comment]
added

**Comment by LukasThyWalls** [comment]
Nice! We can close this issue.
