### ISSUE TITLE
[Bug] Clips' chat and jumping to VOD are out of sync

### ISSUE THREAD

**Issue by Oleepre** [crackededed/Xtra#550]
Since a few days ago I've notice the chat displayed on Clips are way ahead of when they're supposed to show up.
 Testing a bit it seems like:
 - The chat messages displayed are 30 to 60 seconds ahead of time. However in the full VOD they show up correctly.
 - Clicking "Watch full video" will jump to the VOD 30 to 60 seconds ahead of time, regardless of when the button is clicked like at the start of the clip. Ex: A 1 minute clip that starts at 1:00:00, when jumping to the VOD might start at 1:50:00. This behaviour is not consistent even on the same clips, but happens on any channel.
 Currently using latest version of the app.

**Comment by crackededed** [comment]
i checked some clips with desynced chats and they are also desynced when watching from the website
