### ISSUE TITLE
Enhancement : sync VOD progress between Twitch and Xtra ?

### ISSUE THREAD

**Issue by CelianGdfrd** [crackededed/Xtra#552]
That's really a wild guess, but would it be possible to synchronize VOD reading position between Twitch and Xtra ? I like to watch VOD on Twitch web page, but continuing them would really be wild.

Maybe at least a way for Xtra to get the position of some videos at least, like on the Saved tab, an option to sync the position of saved VODs from Twitch ?

**Comment by crackededed** [comment]
#329
