### ISSUE TITLE
Additions for TV users

### ISSUE THREAD

**Issue by ao2323** [crackededed/Xtra#562]
We already know the app is built for mobile. There are many of us that use it on TV as well. 

The main problem is that we can't refresh by swiping down. A refresh button that you can turn on/off would be helpful. 

Another addition that might help all users is a 'Favorites' option that would move your favorite streams to the top of the list .

**Comment by thinkpad4** [comment]
Or a option like Turn on for TV use or leave off for default mobile use

**Comment by Galixte** [comment]
Hi @crackededed 

Could you add a Refresh button on Home page, because the stats and channels online isn’t refreshed when I come back to home page after viewing a channel?

Regards.
