### ISSUE TITLE
Secure App Store

### ISSUE THREAD

**Issue by friendupright** [crackededed/Xtra#566]
What's your opinion on distributing into a secure app store like accrescent? 

Could you do that since fdroid and github releases seem to be insecure and there's no way to verify the installation...

https://github.com/accrescent/accrescent

You would solve the issue with sha-256 fingerprint of the signing keys :(

**Comment by crackededed** [comment]
i think it's still invite only so they don't allow everyone to submit apps yet

**Comment by friendupright** [comment]
I did a year ago. Maybe give it a try and ask the developer on matrix or Twitter

**Comment by crackededed** [comment]
https://github.com/accrescent/accrescent/issues/607
