### ISSUE TITLE
[Bug] Low latency doesn't work with audio-only

### ISSUE THREAD

**Issue by zero13722** [crackededed/Xtra#570]
App version: 2.37.1 (F-droid)
Live target offset: 0-1000ms

Custom buffer works properly with picture on, and I have a stable network connection.
But whenever audio-only is activated, there are usually 5-8 seconds latency during live, no matter what value was set for "live target offset".

**Comment by crackededed** [comment]
i just checked and the buffer settings are applied correctly. there was a lot of buffering when switching to audio only quality but i'm not sure if that's just my connection. latency was fine after refreshing a few times

**Comment by zero13722** [comment]
I've tried to lower min. buffer from 1000 > 10 instead of adjusting live target offset. Somehow now it works with audio-only too! :o

Thanks for confirming.
