### ISSUE TITLE
Videos issue

### ISSUE THREAD

**Issue by nightznero** [crackededed/Xtra#573]
Past broadcast and all doesn't shows up after sorting by "all" (default)
`Following` -> `Videos` -> `Sort`
Type all:
![Screenshot_20241111_205018_Xtra](https://github.com/user-attachments/assets/37385003-c79e-499e-93de-4172efed3e12)
Type past broadcast:
![Screenshot_20241111_205027_Xtra](https://github.com/user-attachments/assets/30dbd6ef-fa31-4d36-85a4-d31d5a4050de)

**Comment by crackededed** [comment]
fixed
