### ISSUE TITLE
Ability to Search Livestreams by Tags or Keywords

### ISSUE THREAD

**Issue by GitHub-Sysadmin** [crackededed/Xtra#581]
It would be helpful to have the ability to search livestreams by specific tags or keywords, such as "mod," "modded," "UK," "US," or "drops." Some games have a massive number of livestreams, and being able to filter streams by tags would allow me to find streams that match my specific interests more easily.

**Comment by crackededed** [comment]
you can tap on the sort bar to search for streams with tags

**Comment by GitHub-Sysadmin** [comment]
Thank you for the response, but the current tag-based system doesn't fully address the issue. Streamers can use custom tags, which means there's no consistent way to filter streams effectively. For example, searching for 'mod' doesn't capture streams tagged with related terms like 'modded' or 'modding,' and it misses streams without relevant tags entirely. In games with hundreds of livestreams, this makes it very difficult to find streams matching specific interests. A more robust search system—such as keyword matching in stream titles, descriptions, and tags—would be much more helpful.

**Comment by crackededed** [comment]
i don't think that's possible with the twitch api
