### ISSUE TITLE
Feature Request: Be able to skip channel prefix for Twitch Emotes

### ISSUE THREAD

**Issue by nullstalgia** [crackededed/Xtra#59]
I'm not sure if this is due to an extension or is standard behavior on the twitch.tv site, but if theres an emote (e.g. `jmikeSadbungle`), you can type `:sadbungle` and you will have the option to press Enter/click it for it to fill out the prefix and any remaining text.

![image](https://user-images.githubusercontent.com/20761757/162846656-0d2d942f-6b7a-4628-9e49-15b87ab424d9.png)

I think this would be a great addition to Xtra if possible!

P.S. Thank you for continuing to work on this amazing app!

**Comment by crackededed** [comment]
should be possible now
