### ISSUE TITLE
"Nothing here" in all Tabs

### ISSUE THREAD

**Issue by Demaar** [crackededed/Xtra#593]
All tabs are empty. 
I can't watch anything.
There isn't even any errors. Just nothing.

**Comment by crackededed** [comment]
does the login page load?

**Comment by Demaar** [comment]
It works now. Was really weird though.
I had already uninstalled the App, so I tried to install it again but it told me that it can't be installed because it's incompatibel with another installed version, so I checked if the app was still there, it wasn't, but when I went to the 'Manage Apps' section of my phone, Xtra was still there and after uninstalling that as well, and installing the newest version it works now.
To answer your question though, Yes, the login page did load and I was able to log in. Though I didn't get any of the 'Do you want to give Xtra access to your account' warnings I got when logging in just now.
