### ISSUE TITLE
[BUG] Replies are shown but can't be made

### ISSUE THREAD

**Issue by SentientCoffee** [crackededed/Xtra#594]
When chatting with version 2.39.3 and above, seeing other people's replies works fine, but trying to reply to someone yourself doesn't work. It will send the chat normally, but it won't show as a reply to the person you "replied" to.

Steps to reproduce:
1. Open a twitch chat with a least one other person chatting
2. Tap the other chatter's message and hit "Reply"
3. See the message you're "replying" to above the text input, type out any message and hit "Send"
4. See the reply in chat only appear as a normal chat, without the message you replied to above the message like other replies

**Comment by crackededed** [comment]
what version are you using exactly? i just tried with a fresh install on latest and it seemed to work for me

**Comment by SentientCoffee** [comment]
Currently using 2.39.3

**Comment by SentientCoffee** [comment]
https://github.com/user-attachments/assets/89bbb7ae-5ebe-48a4-bff9-c08557455121

Example of reproducing the bug.
I'm on a Pixel 6 with GrapheneOS, if that helps.

**Comment by crackededed** [comment]
do you have `Send chat messages using api` enabled at the bottom of the settings? it needs to be turned off right now but i'll fix it

**Comment by SentientCoffee** [comment]
I did have that enabled. Confirmed it works when disabled after an app restart. Thanks!
