### ISSUE TITLE
Support background audio

### ISSUE THREAD

**Issue by Sytten** [crackededed/Xtra#60]
Hello! Super grateful for the fork that works so well.

I saw that there was a closed issue to support background audio player, so I figured I could reopen one to see if now you knew how to support it?

Usually we need a permanent notification to support that. Never done it myself but I guess I could try if thats not a priority for you you :)

**Comment by Sytten** [comment]
Let me try with the latest version, I didn't see it. 
One thing nice with newpipe that could be implemented is the auto-switch to audio when the phone is closed.

**Comment by crackededed** [comment]
yeah that would be nice

**Comment by crackededed** [comment]
i think it works now

**Comment by Sytten** [comment]
Yup works great! Thanks a lot :)

**Comment by Sytten** [comment]
@crackededed Small suggestion, you could version your releases so its a bit easier to keep track of where you are vs the current release.

**Comment by Sytten** [comment]
There is a small bug, if the stream is paused and you close the phone / app it restarts it in the background.

**Comment by crackededed** [comment]
there's no play button on the notification so you can't unpause anyway. should i add that? or maybe the audio player should just not start

**Comment by Sytten** [comment]
There is a play/stop button in the notification on my phone. But yeah dont start a background play if the stream is paused in the app.

![Screenshot_2022-05-03-09-15-14-442_bitpit.launcher.jpg](https://user-images.githubusercontent.com/2366731/166459595-e09c46f4-bb5c-412e-8a5a-dcef0137a1f3.jpg)

**Comment by crackededed** [comment]
fixed
