### ISSUE TITLE
[FEATURE REQUEST] Unmuted downloaded VODs 

### ISSUE THREAD

**Issue by HydroSpaceTurbine** [crackededed/Xtra#600]
Would it be possible to implement this:
when I download the specific muted parts of VODs it will be unmuted?

https://github.com/TwitchRecover/TwitchRecover
https://github.com/MacielG1/VodRecovery
https://github.com/devhotteok/TwitchLink

**Comment by crackededed** [comment]
do they still work? can you link any vods that can be unmuted right now?

**Comment by HydroSpaceTurbine** [comment]
Sorry for the late reply

Here's a VOD with muted parts (highlighted by dark reddish color)

https://www.twitch.tv/videos/2339369348
(Also all of this streamer's VODs gets muted as he always plays music)

On the links, unfortunately, I don't know if they're working as I don't have a PC/laptop.

**Comment by crackededed** [comment]
this vod doesn't seem to have any unmuted segments available. i'm guessing vods can't really be unmuted anymore because the unmuted segments are deleted so fast
