### ISSUE TITLE
Feature Request: Saving Sorting Per Channel or In General

### ISSUE THREAD

**Issue by KaiserCalm** [crackededed/Xtra#65]
Save what is chosen in this menu per channel or just in general. Maybe a button at the top or bottom of the menu that says "Remember/Save Choices for Channel" and then a default in the settings. It doesn't have to be done this way, it just has to somehow remember the choices in that menu.
![Screenshot_20220428-192938](https://user-images.githubusercontent.com/81613945/165800503-814a6075-25dc-46dd-a7b4-a18d12f4c3ff.jpg)
Also, I'll take a moment to say, great job and thank you on maintaining and improving the app!

**Comment by crackededed** [comment]
added

**Comment by KaiserCalm** [comment]
Thank you so much!
