### ISSUE TITLE
Audio only

### ISSUE THREAD

**Issue by zwij** [crackededed/Xtra#67]
When i choose audio only, lock screen, unlock, exit stream (click back and swipe right), audio keeps playing, even when i go on home screen. I have to kill the app. Similar issue happens, when i choose audio only, lock screen, unlock and choose "source" quality. Then i hear double audio (one has delay). Then when i exit stream (click back and swipe right) happens the issue i wrote first... audio remains on home screen, have to kill the app. Samsung A52s 5G, Android 12. (sorry for my english)

**Comment by crackededed** [comment]
fixed
