### ISSUE TITLE
[BUG] Latest Exoplayer releases causing stuttering while streaming

### ISSUE THREAD

**Issue by MF-Debug** [crackededed/Xtra#69]
Latest build is causing lag while streaming in source quality or even 720p. It streams fine for 480p but the quality is bad. I've reverted back to the build prior to exoplayer attached in the ss & everything is now fine.

My Device: Samsung Galaxy Note 3 SM-N9005
ROM: LOS 17.1

![image](https://user-images.githubusercontent.com/6173607/166315162-9254ad80-62fa-462c-a603-5d5601fe722b.png)

**Comment by crackededed** [comment]
try the new version with default settings. on the first updated exoplayer build the stream delay was set to 1 second and that requires a really good internet. it's now set to 5s but if you had the first build installed it's still probably set to 1s. you can change it manually in settings -> buffer settings.

![Screenshot_20220503_112216](https://user-images.githubusercontent.com/90209774/166423584-88191a6a-2144-4d65-94cb-86206b793812.png)

**Comment by MF-Debug** [comment]
Buffer settings are exactly as the screenshot. The streaming itself is working fine, the video plays with constant hitching. I've provided a recording (source quality) of the latest build to understand the issue.

https://user-images.githubusercontent.com/6173607/166428304-3f7c68f8-064e-4f61-a645-6cfa66c4d03b.mp4

The hitching continues even if I close chat & go full-screen, so I recorded it this way. I think I couldn't explain the issue properly before, my bad. Apologies as English is not my first language.

**Comment by crackededed** [comment]
does it happen on videos too or live only?

**Comment by MF-Debug** [comment]
just tested, same for videos too.

**Comment by crackededed** [comment]
i made a version that has the old exoplayer. try using that

**Comment by MF-Debug** [comment]
old xoplayer one works fine. thanks for this, I'll close this issue.

**Comment by crackededed** [comment]
i just dug up an old phone for testing and it's actually the same model you mentioned here: SM-N9005. so i tested some firmwares. on stock android 5.0 xtra worked fine, no lag. then i tried some unofficial lineage os 17.1 and it lagged like in your video. then i tried los 18.1 and there was no lag on 1080p60. everything seemed to work fine from what i tested. so if you want to try newer los you can get it from this site: https://download.lineageos.org/hlte

**Comment by MF-Debug** [comment]
To be honest, I don't like the newer android versions after android 10. That's why I am stuck with the last official LOS 17.1 build. I'll get some free time to upgrade to 18.1 if it fixes the issue. I'll let you know if it's fixed on my side after that.

**Comment by MF-Debug** [comment]
Hi, I finally got time to upgrade to LOS 18.1 & the issue seems to be fixed as you mentioned earlier. You can drop support for old exoplayer build if you want. Thank you for maintaining it up until now.
