### ISSUE TITLE
"Audio only" issue

### ISSUE THREAD

**Issue by lukasquo** [crackededed/Xtra#7]
whenever i change the stream quality to audio only, the app crashes

**Comment by jojobozo** [comment]
It's working fine for me

**Comment by crackededed** [comment]
what android version are you on?

**Comment by lukasquo** [comment]
android 12 on galaxy s21 (not sure if you need more detailed info)

**Comment by crackededed** [comment]
problem is that xtra uses an older version of exoplayer. on newer versions this crash doesn't happen. so if i figure out how to migrate to the new version at some point this issue will be fixed

**Comment by lukasquo** [comment]
alright, thanks
