### ISSUE TITLE
Bug: Paused video in app is restarted on background audio

### ISSUE THREAD

**Issue by Sytten** [crackededed/Xtra#71]
Hello!

I am using the following settings:
- Background playback: audio only
- Keep audio playing when screen is off: on

If the video is paused in the app, it is restarted when closing the phone or the application.

Same thing happens when unplugging headphones too (I can open a different issue for that).

**Comment by crackededed** [comment]
try the new version

**Comment by Sytten** [comment]
Seems to be fixed!
