### ISSUE TITLE
Feature Request: Youtube-DL addond

### ISSUE THREAD

**Issue by CrazyWolf13** [crackededed/Xtra#80]
Hello there 
I really like your twitch player, its genius.

But i'd like to see one more feature:
Be able to download streams directly cause most music streams get muted.
So i mean like capture a livestream live.

This could be easily possible with an integration for the very famous Youtube-DL wouldn't be sooo much to add.

Thanks for developing and your reply
Best Regards

**Comment by CrazySaft** [comment]
If you would like me to, i could translate your app to German as a compensation. 😂

**Comment by thinkpad4** [comment]
@CrazySaft That seems like it would be very difficult, YT-DL uses command line input, that would add a lot of settings to the app.

**Comment by CrazySaft** [comment]
> @CrazySaft That seems like it would be very difficult, YT-DL uses command line input, that would add a lot of settings to the app.

Oh I'm sorry i meant like the base with youtube-dl is already there and i thought this could be made easy.

**Comment by crackededed** [comment]
can the android version even download livestreams?

**Comment by CrazySaft** [comment]
> can the android version even download livestreams?
Uhhm i think so 
I think with the corecct libraries and so it's possible.

I found this here 
https://github.com/yausername/youtubedl-android
This and FFMPEG should work on android

**Comment by CrazySaft** [comment]
> can the android version even download livestreams?

I tested the application i linked and its a exact replyca of Youtube-DL it even works with custom commands and it could download streams.

**Comment by thinkpad4** [comment]
@crackededed If you end up adding this can it please be it's own version like you have for API16 and English Only?   Thank you very much

**Comment by crackededed** [comment]
> @crackededed If you end up adding this can it please be it's own version like you have for API16 and English Only? Thank you very much

yeah i guess. but why?

**Comment by CrazySaft** [comment]
> > @crackededed If you end up adding this can it please be it's own version like you have for API16 and English Only? Thank you very much
> 
> yeah i guess. but why?

A short question neraby: Do you need help with translating your application to German?

**Comment by crackededed** [comment]
> > > @crackededed If you end up adding this can it please be it's own version like you have for API16 and English Only? Thank you very much
> > 
> > 
> > yeah i guess. but why?
> 
> A short question neraby: Do you need help with translating your application to German?

yes

**Comment by CrazySaft** [comment]
> > > > @crackededed If you end up adding this can it please be it's own version like you have for API16 and English Only? Thank you very much
> > > 
> > > 
> > > yeah i guess. but why?
> > 
> > 
> > A short question neraby: Do you need help with translating your application to German?
> 
> yes

So what should i translate?
Have you got an file with the text?

**Comment by crackededed** [comment]
> > > > > @crackededed If you end up adding this can it please be it's own version like you have for API16 and English Only? Thank you very much
> > > > 
> > > > 
> > > > yeah i guess. but why?
> > > 
> > > 
> > > A short question neraby: Do you need help with translating your application to German?
> > 
> > 
> > yes
> 
> So what should i translate? Have you got an file with the text?

here are the files:
[strings.xml](https://github.com/crackededed/Xtra/blob/master/app/src/main/res/values/strings.xml)
[plurals.xml](https://github.com/crackededed/Xtra/blob/master/app/src/main/res/values/plurals.xml)

**Comment by thinkpad4** [comment]
> Because if you add YT-DL and FFMpeg the app won't be a nice lightweight file size anymore

**Comment by crackededed** [comment]
seems like every recording starts with the "commercial break in progress" screen. this could be fixed by changing some headers when getting the playback token but i don't see any commands or anything that would let me do that. and the apk is like 60mb with this library. so i think some other way of recording streams is probably needed.

**Comment by CrazySaft** [comment]
> seems like every recording starts with the "commercial break in progress" screen. this could be fixed by changing some headers when getting the playback token but i don't see any commands or anything that would let me do that. and the apk is like 60mb with this library. so i think some 
other way of recording streams is probably needed.

This Screen doesn't really bother me cause its 15 seconds which could be easily cut away or skippt (maybe in future automated), okay, that's a bit bad, but i understand, maybe a lightweight version of youtube-dl or so or maybe there are other applications, but if something like this would be possible, this would be great.

May you have got any other ideas how to do this without Youtube-DL.

**Comment by AndreyAsadchy** [comment]
There is CacheDataSource/SimpleCache in exoplayer, maybe it would work

**Comment by thinkpad4** [comment]
>  the apk is like 60mb with this library.  This is why I asked if this is added or something like it, it be it's own apk release not part of the main or english only apks.

**Comment by CrazySaft** [comment]
> seems like every recording starts with the "commercial break in progress" screen. this could be fixed by changing some headers when getting the playback token but i don't see any commands or anything that would let me do that. and the apk is like 60mb with this library. so i think some other way of recording streams is probably needed.

So what do you mean? Do you think this is somethig you woul add or rather not?

**Comment by crackededed** [comment]
> > seems like every recording starts with the "commercial break in progress" screen. this could be fixed by changing some headers when getting the playback token but i don't see any commands or anything that would let me do that. and the apk is like 60mb with this library. so i think some other way of recording streams is probably needed.
> 
> So what do you mean? Do you think this is somethig you woul add or rather not?

not going to add yt-dl

**Comment by CrazySaft** [comment]
> > > seems like every recording starts with the "commercial break in progress" screen. this could be fixed by changing some headers when getting the playback token but i don't see any commands or anything that would let me do that. and the apk is like 60mb with this library. so i think some other way of recording streams is probably needed.
> > 
> > 
> > So what do you mean? Do you think this is somethig you woul add or rather not?
> 
> not going to add yt-dl

So you mean no live download feature?
Or just not YT-DL
