### ISSUE TITLE
Feature Request Button To Toggle AudioOnly On/Off

### ISSUE THREAD

**Issue by MrX101** [crackededed/Xtra#92]
Basically going to the setting menu to switch to audio only is pretty annoying, especially since you need to wait for the stream to load, after you change it. So you can't just quickly change between screen mode and audio only when you need to get off the bus or whatever. 

As such, I think a button to toggle between AudioOnly and last set video bitrate would be super useful. Especially on the Picture In Picture screen.

Also, an option to automatically switch to audioOnly when you turn off the phone screen, would be a very appreciated addition too!. 

Don't know if you accept donations, but willing to donate 100$ to get this done quicker if possible!

**Comment by crackededed** [comment]
there is a setting called: Keep audio playing when screen is off. doesn't that do what you want?

**Comment by MrX101** [comment]
Ahh somehow didn't see that setting and I checked them like 5 times xD.

A button to quickly go to audio only mode on the player itself would still be nice though, since it takes about 5-7 sec for the stream to load after you lock the phone.

**Comment by crackededed** [comment]
a button would just do the same thing as the menu option. you would still have to wait for it to load. so maybe making the switch to audio only smoother should be the goal

**Comment by MrX101** [comment]
well the button is simply to save me having to click the cogwheel then the change to audio only mode, for when I still want to read chat, but don't want video. I tend to toggle between "Audio Only" and "auto" quite often. 

The toggle would just be very convenient but fair enough if you don't feel like it's necessary.

**Comment by MrX101** [comment]
Thank you, works great!

Do you have a link for donations?

**Comment by crackededed** [comment]
i don't
