### ISSUE TITLE
Sorting followed channels by last broadcast shows users w/o broadcasts at the top

### ISSUE THREAD

**Issue by adem4ik** [crackededed/Xtra#94]
1. Login to Twicth acc
2. Go to Following - Channels
3. Use the following sorting: Last broadcast, Descending
![image](https://user-images.githubusercontent.com/4707112/175303903-66c5e071-8c57-4c4b-83f3-2e78b289b7ec.png)

**Expected result:** users w/o any broadcasts should be at the end of the list
**Result:** a few users w/o any broadcasts (just friends) are shown at the top
![image](https://user-images.githubusercontent.com/4707112/175305151-d9a669e7-c0e3-4a25-8e25-ef32549c410b.png)

**Comment by crackededed** [comment]
should be fixed now

**Comment by adem4ik** [comment]
I've installed the latest apk (2.0.2) - unfortunately it is not, here is comparison for Descending/Ascending:
![image](https://user-images.githubusercontent.com/4707112/175547748-a61f53b4-648f-42df-8205-4ff67a0a4dca.png) ![image](https://user-images.githubusercontent.com/4707112/175547836-28fb7d97-751b-42cf-942f-67ef5e2e08d4.png)

**Comment by crackededed** [comment]
fixed
