### ISSUE TITLE
Fast forward/rewind buttons are incorrect for 15/60 sesonds

### ISSUE THREAD

**Issue by adem4ik** [crackededed/Xtra#96]
Version: 2.0.2

Problem:
- User can set 5/10/15/30/60 seconds.
- But Fast forward/Rewind buttons show only 5/10/30 seconds, cause there are only pictures for them:
https://github.com/crackededed/Xtra/blob/bdb2ece000d51cd978bf76bff4b6fad3c276f934/app/src/main/java/com/github/andreyasadchy/xtra/ui/player/BasePlayerFragment.kt#L222-L230

So the following case is possible now:
- Settings:
![image](https://user-images.githubusercontent.com/4707112/175693223-71eb7394-886b-4734-8ad2-8e1ae544d969.png)

- Player:
![image](https://user-images.githubusercontent.com/4707112/175692435-72dc1d6c-ecef-4524-adcd-a7e5db276a02.png)

P.S. I can draw buttons for 15/60 seconds. Ping me, if you need.

**Comment by crackededed** [comment]
yes make those new pictures if possible
