### ISSUE TITLE
Recent Apps Menu and Picture in Picture

### ISSUE THREAD

**Issue by haitham506** [crackededed/Xtra#99]
Hello,

If I hit Recent Apps Menu to Switch to another app while watching a stream the Picture in Picture doesn't work, I have to go home first for the PiP to work then open another app. Is this fixable?

Thank you :)

**Comment by r-u-e** [comment]
> should work now

still not work for me all recent patches
android15 device

**Comment by r-u-e** [comment]
also when check stremer homepage about link, click chat share links to browser, didn't atuo pip but stop playing
